<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GuessWord;

class GuessWordSeeder extends Seeder
{
    public function run(): void
    {
        $kabanatas = [
            1 => [
                ['question' => 'TAO (11 titik): Siya ang nagging kura paroko ng San Diego sa loob ng dalawampung taon.', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TITULO/POSISYON (7 titik): Siya ang kinikilalang kinatawan ng hari sa Pilipinas.', 'answer' => 'HENERAL'],
                ['question' => 'TAO (11 titik): Siya ang paring nag awat sa pagtatalo ng tenyente at ni Padre Damaso.', 'answer' => 'PADRE SIBYLA'],
                ['question' => 'LUGAR (7 titik): Saang pook nakatirik ang bahay ni Kapitan Tiago.', 'answer' => 'BINUNDOK'],
                ['question' => 'PANAHON/TAGAL (9 titik): Gaano katagal nanungkulan si Padre Damaso sa San Diego.', 'answer' => 'DALAWAMPU'],
                ['question' => 'PANINIWALA/DESKRIPSYON (11 titik): Ayon sa kanya, ang mga Indio raw ay likas na ___.', 'answer' => 'MAPAGPABAYA'],
                ['question' => 'TAO, MAY INISYAL (7 titik): Siya ang nagpahayag na ang mga Indio ay mangmang at walang malasakit.', 'answer' => 'G LARUJA'],
                ['question' => 'TAO (14 titik): Siya ang mapagpanggap na asawa ni Dr. de Espadana.', 'answer' => 'DONYA VICTORINA'],
                ['question' => 'KAISIPAN/KAUGALIANG FILIPINO (11 titik): Ayon kay G. Laruja, kulang daw ang mga Indio sa ______.', 'answer' => 'UTANG NA LOOB'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang nadama ni Padre Damaso hanggang muntik mabitawan ang hawak na kopita.', 'answer' => 'NABIGLA'],
            ],
            2 => [
                ['question' => 'TAO (18 titik): Siya ang binatang bagong balik mula sa pag-aaral sa Europa.', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'PANAHON/TAGAL (4 titik): Ilang taon nanatili si Ibarra sa Europa para mag-aral.', 'answer' => 'PITO'],
                ['question' => 'TAO (13 titik): Siya ang matalik na kakilala ng ama ni Ibarra na nag-imbita ng pananghalian.', 'answer' => 'KAPITAN TINONG'],
                ['question' => 'TAO (12 titik): Siya ang nagpakilala kay Ibarra sa salusalo.', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (11 titik): Siya ang ama ni Crisostomo Ibarra.', 'answer' => 'DON RAFAEL'],
                ['question' => 'GRUPO (6 titik): Kaninong umpukan lumapit si Ibarra upang makipagkilala.', 'answer' => 'BINATA'],
                ['question' => 'TAO (11 titik): Sino ang kanyang nakilala sa umpukan.', 'answer' => 'ISANG MAKATA'],
                ['question' => 'BAGAY/SINING (4 titik): Ano ang muling nagpaalab ng pagmamahal ni Ibarra sa bayan habang kausap ang makata.', 'answer' => 'TULA'],
                ['question' => 'LUGAR (8 titik): Tinanggihan ni Ibarra ang alok na pananghalian dahil siya ay uuwi na sa ______.', 'answer' => 'SAN DIEGO'],
                ['question' => 'PANGALAN (8 titik): Juan Crisostomo Ibarra y ____________, ang buong pangalan ni Ibarra.', 'answer' => 'MAGSALIN'],
            ],
            3 => [
                ['question' => 'PAGKAIN (6 titik): Anong ulam ang inihanda ni Kapitan Tiago sa salusalo?', 'answer' => 'TINOLA'],
                ['question' => 'ALAALA (8 titik): Ano ang nagbalik ng gunita kay Ibarra nang maalala ang sinabi ng kanyang dating kura?', 'answer' => 'KABATAAN'],
                ['question' => 'BAGAY (9 titik): Ano ang tinukoy tungkol sa "luklukan" o upuan sa larawan?', 'answer' => 'KOMPESOR'],
                ['question' => 'BAGAY (8 titik): Ano ang pinag-aagawan nina Padre Damaso at Padre Sibyla?', 'answer' => 'KABISERA'],
                ['question' => 'LUGAR (6 titik): Saang pook namalagi si Ibarra bago siya bumalik sa bayan?', 'answer' => 'EUROPA'],
                ['question' => 'BANSA (7 titik): Itinuturing ni Ibarra na pangalawang inang bayan.', 'answer' => 'ESPANYA'],
                ['question' => 'PAGKAIN (12 titik): Anong bahagi ng manok ang napunta kay Padre Damaso kaya\'t binagsak niya ang kutsara\'t tinulak ang pinggan?', 'answer' => 'LEEG AT PAKPAK'],
                ['question' => 'KATANGIAN (11 titik): Ayon kay Padre Damaso, ano ang kasamaan na dulot ng pagpapaaral sa Europa?', 'answer' => 'MAPAGMATAAS'],
                ['question' => 'BAGAY (9 titik): Sa kanilang pagtatalo, ano ang sinabi ni Padre Sibyla na dapat mapunta kay Padre Damaso?', 'answer' => 'LUKLUKAN'],
                ['question' => 'ARALIN (10 titik): Ano ang unang pinag-aralan ni Ibarra bago siya tumungo sa isang bayan?', 'answer' => 'KASAYSAYAN'],
            ],
            4 => [
                ['question' => 'TAO (6 titik): Sino ang inilalarawan na naglalakad at walang tiyak na patutunguhan?', 'answer' => 'IBARRA'],
                ['question' => 'LUGAR (8 titik): Saan nakarating si Ibarra habang siya\'y naglalakad?', 'answer' => 'BINUNDOK'],
                ['question' => 'TAO (11 titik): Sino ang pinasasaringan ni Padre Damaso sa kanyang sermon?', 'answer' => 'DON RAFAEL'],
                ['question' => 'LUGAR (7 titik): Saan pinasasaringan ni Padre Damaso ang ama ni Ibarra?', 'answer' => 'PULPITO'],
                ['question' => 'KATANGIAN (11 titik): Saan nakilala ang dating artilyero na natanggal sa pagiging sundalo?', 'answer' => 'KAMANGMANGAN'],
                ['question' => 'PARATANG (11 titik): Ano ang ibinintang sa ama ni Ibarra?', 'answer' => 'PILIBUSTERO'],
                ['question' => 'TAO (9 titik): Siya ang sumuka ng dugo at kalaunan ay namatay.', 'answer' => 'ARTILYERO'],
                ['question' => 'PARATANG (12 titik): Ano pa ang isinakdal sa ama ni Ibarra bukod sa pagiging pilibustero?', 'answer' => 'NANGAMKAM'],
                ['question' => 'LUGAR (12 titik): Saan nagpahatid si Ibarra matapos ang usapan nila ng tenyente?', 'answer' => 'FONDA DE LALA'],
                ['question' => 'SASAKYAN (6 titik): Ano ang sinakyan ni Ibarra papuntang Fonda de Lala?', 'answer' => 'KALESA'],
            ],
            5 => [
                ['question' => 'DAMDAMIN (13 titik): Ano ang naramdaman ni Ibarra nang siya\'y umupo sa isang silyon?', 'answer' => 'BALISANG-BALISA'],
                ['question' => 'PANGITAIN (14 titik): Sa pangitain ni Ibarra, sino ang binatang masayang nakita niya sa ibayong dagat?', 'answer' => 'KANYANG SARILI'],
                ['question' => 'BAHAGI NG SILID (10 titik): Saang bahagi ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?', 'answer' => 'DURUNGAWAN'],
                ['question' => 'TAO (11 titik): Sino ang magandang dilag na nakita ni Ibarra na nakadamit Pilipina?', 'answer' => 'MARIA CLARA'],
                ['question' => 'INSTRUMENTO (7 titik): Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra.', 'answer' => 'BIYULIN'],
                ['question' => 'TAO (11 titik): Sino ang palaging laman ng isip ni Ibarra?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (8 titik): Saan nagmula si Maria Clara?', 'answer' => 'BEATERYO'],
                ['question' => 'BILANG (6 titik): Ilan ang pangitain na nasilayan ni Ibarra sa kalawakan?', 'answer' => 'DALAWA'],
                ['question' => 'TAO (3 titik): Sa kanyang pangitain, sino ang lalaking nakita ni Ibarra na nagdurusa sa kulungan?', 'answer' => 'AMA'],
                ['question' => 'BAGAY (4 titik): Ano ang namatay sa katapat na bahay Ibarra?', 'answer' => 'ILAW'],
            ],
            6 => [
                ['question' => 'DAMDAMIN (13 titik): Ano ang naramdaman ni Ibarra nang siya\'y umupo sa isang silyon?', 'answer' => 'BALISANG-BALISA'],
                ['question' => 'PANGITAIN (14 titik): Sa pangitain ni Ibarra, sino ang binatang masayang nakita niya sa ibayong dagat?', 'answer' => 'KANYANG SARILI'],
                ['question' => 'BAHAGI NG SILID (10 titik): Saang bahagi ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?', 'answer' => 'DURUNGAWAN'],
                ['question' => 'TAO (11 titik): Sino ang magandang dilag na nakita ni Ibarra na nakadamit Pilipina?', 'answer' => 'MARIA CLARA'],
                ['question' => 'INSTRUMENTO (7 titik): Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra.', 'answer' => 'BIYULIN'],
                ['question' => 'TAO (11 titik): Sino ang palaging laman ng isip ni Ibarra?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (8 titik): Saan nagmula si Maria Clara?', 'answer' => 'BEATERYO'],
                ['question' => 'BILANG (6 titik): Ilan ang pangitain na nasilayan ni Ibarra sa kalawakan?', 'answer' => 'DALAWA'],
                ['question' => 'TAO (3 titik): Sa kanyang pangitain, sino ang lalaking nakita ni Ibarra na nagdurusa sa kulungan?', 'answer' => 'AMA'],
                ['question' => 'BAGAY (4 titik): Ano ang namatay sa katapat na bahay Ibarra?', 'answer' => 'ILAW'],
            ],
            7 => [
                ['question' => 'GAWAIN (8 titik): Si Maria Clara ay nagtatanggal ng inip sa pamamagitan ng _____.', 'answer' => 'PANANAHI'],
                ['question' => 'TAO (13 titik): Sino ang nagpayo kay Maria Clara na magbakasyon muna sa San Diego o Malabon?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'KATANGIAN (9 titik): Ano ang napansin ni Kapitan Tiago kay Maria Clara?', 'answer' => 'NAMUMUTLA'],
                ['question' => 'BAGAY (8 titik): Ano ang tumigil sa tapat ng bahay nina Maria Clara dahilan para mawalan siya ng kulay?', 'answer' => 'SASAKYAN'],
                ['question' => 'LUGAR (6 titik): Saang paaralan nag-aral si Ibarra nang siya ay bata pa?', 'answer' => 'ATENEO'],
                ['question' => 'WIKA (5 titik): Anong wika ang ginagamit ni Ibarra sa pagtuturo ng mga pangalan ng bulaklak?', 'answer' => 'LATIN'],
                ['question' => 'HALAMAN (4 titik): Anong uri ng bulaklak ang ginamit sa putong?', 'answer' => 'SUHA'],
                ['question' => 'PANGALAN (5 titik): Ano ang pangalan na itinawag ni Ibarra kay Maria Clara?', 'answer' => 'CHLOE'],
                ['question' => 'DAMDAMIN (5 titik): Ano ang naramdaman ni Ibarra nang siya ay tawanan ni Maria Clara?', 'answer' => 'TAMPO'],
                ['question' => 'HALAMAN (7 titik): Ang halamang inilagay sa loob ng sombrero ay _____.', 'answer' => 'SAMBONG'],
            ],
            8 => [
                ['question' => 'SASAKYAN (6 titik): Si Ibarra ay sakay ng _____ papunta sa Maynila.', 'answer' => 'KALESA'],
                ['question' => 'GAWAIN (10 titik): Ano ang ginagawa ng mga bilanggo sa larawan?', 'answer' => 'NAGPIPISON'],
                ['question' => 'AMOY (6 titik): Anong amoy ang nakapagpaalala kay Ibarra ng kanyang pagkahilo?', 'answer' => 'TABAKO'],
                ['question' => 'LUGAR (14 titik): Ano ang naalala ni Ibarra sa Europa na umaakit sa maraming tao?', 'answer' => 'HARDING BOTANIKO'],
                ['question' => 'LUGAR (6 titik): Ano ang nakita ni Ibarra na naliligid ng makakapal na pader?', 'answer' => 'MAYNILA'],
                ['question' => 'TAO (11 titik): Sino ang nagbigay ng bilin kay Ibarra bago siya umalis ng Europa?', 'answer' => 'GURONG PARI'],
                ['question' => 'BAGAY (5 titik): Ano ang sinadya ng mga banyaga sa bayan?', 'answer' => 'GINTO'],
                ['question' => 'TAO (13 titik): Sino ang naraanan ni Ibarra na nakatanikala at nagpipison ng bato?', 'answer' => 'ILANG BILANGGO'],
                ['question' => 'TAO (12 titik): Sino ang namataan ni Ibarra sa magandang karwahe na nakakunot-noo?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (10 titik): Ang punong talisay na nakita ni Ibarra ay sa lugar ng _____.', 'answer' => 'SAN GABRIEL'],
            ],
            9 => [
                ['question' => 'LUGAR (8 titik): Si Maria Clara ay nagtungo sa _____ upang kunin ang kanyang mga kagamitan.', 'answer' => 'BEATERYO'],
                ['question' => 'TAO (12 titik): Sino ang dumating at nagtanong kina Tiya Isabel at Maria Clara kung saan sila patungo?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (10 titik): Sino ang kasama ni Maria Clara sa karwahe?', 'answer' => 'TIYA ISABEL'],
                ['question' => 'TAO (12 titik): Sino ang nagtungo sa kumbento matapos magmisa?', 'answer' => 'PADRE SIBYLA'],
                ['question' => 'LUGAR (8 titik): Saang lugar nagtungo si Padre Sibyla pagkatapos ng misa?', 'answer' => 'KUMBENTO'],
                ['question' => 'TAO (6 titik): Sino ang mapapangasawa ni Maria Clara?', 'answer' => 'IBARRA'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang naramdaman ni Kapitan Tiago sa di-karaniwang anyo ni Padre Damaso?', 'answer' => 'NABAHALA'],
                ['question' => 'TAO (15 titik): Kanino nakarating ang nangyari, kaya\'t pinaalis si Padre Damaso?', 'answer' => 'KAPITAN HENERAL'],
                ['question' => 'BAGAY (12 titik): Ano ang pinatay ni Kapitan Tiago patungkol sa paglalakbay ni Ibarra?', 'answer' => 'ILAW AT KANDILA'],
                ['question' => 'TAO (11 titik): Kanino ibinilin ni Kapitan Tiago na itulos ang ilaw at kandila nang umalis si Ibarra?', 'answer' => 'MARIA CLARA'],
            ],
            10 => [
                ['question' => 'LUGAR (8 titik): Ang bayan ng _____ ay matatagpuan malapit sa baybayin ng lawa.', 'answer' => 'SAN DIEGO'],
                ['question' => 'UGALI (9 titik): Ano ang dahilan kung bakit ang mga inaani sa bayan ay binibili ng mga Tsino sa murang halaga?', 'answer' => 'KAHANGALAN'],
                ['question' => 'TAO (4 titik): Sino ang bumibili sa murang halaga ng mga inaani ng mga tao sa San Diego?', 'answer' => 'TSINO'],
                ['question' => 'LUGAR (4 titik): Ano ang natuklasan ng matandang Kastila sa gubat na dinadaluyan ng mainit na tubig?', 'answer' => 'POOK'],
                ['question' => 'BAGAY (5 titik): Bukod sa mga damit at salapi, ano pa ang ibinayad ng matandang Kastila?', 'answer' => 'HIYAS'],
                ['question' => 'KUWENTO (5 titik): Ano ang dahilan kung bakit iginagalang ng mga tao ang gubat?', 'answer' => 'ALAMAT'],
                ['question' => 'TAO (9 titik): Sino ang nakatagpo sa matandang Kastila na nakabitin sa puno?', 'answer' => 'MGA PASTOL'],
                ['question' => 'BAGAY (5 titik): Ano ang mga pinagtatapon ng mga babae sa ilog?', 'answer' => 'HIYAS'],
                ['question' => 'TAO (8 titik): Sino ang natagpuan ng mga pastol na nakabitin sa puno?', 'answer' => 'ANG MATANDA'],
                ['question' => 'TAO (9 titik): Sino ang binatang mestiso na dumating sa pook na nabili ng matandang Kastila?', 'answer' => 'SATURNINO'],
            ],
            11 => [
                ['question' => 'TAO (11 titik): Si _____ ang pinakamayamang tao sa bayan ng San Diego.', 'answer' => 'DON RAFAEL'],
                ['question' => 'TAO (16 titik): Sino ang madalas pagtawanan at tinatawag na "Sakristang Tiago"?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (11 titik): Sino ang humalili kay Padre Damaso nang siya ay maalis sa San Diego?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (7 titik): Sino ang asawa ni Donya Consolacion?', 'answer' => 'ALPERES'],
                ['question' => 'KATUNGKULAN (4 titik): Kaninong kapangyarihan ang inihahalintulad sa Papa sa Batikano?', 'answer' => 'KURA'],
                ['question' => 'GAWAIN (9 titik): Ano ang hilig ni Padre Salvi bukod sa pangingilin?', 'answer' => 'PAGAAYUNO'],
                ['question' => 'TAO (16 titik): Ang Alperes ay sawimpalad dahil sa pagkakapag-asawa kay _____.', 'answer' => 'DONYA CONSOLACION'],
                ['question' => 'GAWAIN (8 titik): Kapag pumapasok ang Alperes, ano ang iniuutos ni Padre Salvi sa sakristan?', 'answer' => 'ISARA ANG PINTO'],
                ['question' => 'DAMIT (7 titik): Ano ang suot ni Donya Consolacion habang nakadungaw?', 'answer' => 'PRANELA'],
                ['question' => 'KATANGIAN (9 titik): Ano ang hitsura ng mga mata ni Donya Consolacion?', 'answer' => 'NANLILISIK'],
            ],
            12 => [
                ['question' => 'BAGAY (4 titik): Sa gitna ng libingan ay may nakatuntong sa bato --- isang _____.', 'answer' => 'KRUS'],
                ['question' => 'LUGAR (8 titik): Ano ang nasa dulo ng makipot na landas sa San Diego?', 'answer' => 'LIBINGAN'],
                ['question' => 'BILANG (6 titik): Ilang tao ang humuhukay ng paglilibingan sa tabi ng pader?', 'answer' => 'DALAWA'],
                ['question' => 'BAGAY (5 titik): Ano ang hinahanap ng matanda na lumapit sa tagapaglibing?', 'answer' => 'BUNGKO'],
                ['question' => 'KATANGIAN (6 titik): Ano ang hitsura ng paligid ng libingan?', 'answer' => 'MASUKAL'],
                ['question' => 'HALAMAN (15 titik): Ano ang nagsisilbing palamuti sa mga bangkay?', 'answer' => 'DAMO AT HALAMAN'],
                ['question' => 'PANGYAYARI (8 titik): Ano ang maaaring mangyari sa pader na katabi ng hinuhukay?', 'answer' => 'BABAGSAK'],
                ['question' => 'BAGAY (12 titik): Sa paanan ng krus, ano ang nakatambak?', 'answer' => 'BUNGKO AT BUTO'],
                ['question' => 'GAWAIN (9 titik): Ano ang ginagawa ng matanda habang lumalapit?', 'answer' => 'NAGHANAP'],
                ['question' => 'BAGAY (6 titik): Ano ang dinukot ng matanda mula sa kanyang bulsa?', 'answer' => 'SALAPI'],
            ],
            13 => [
                ['question' => 'SASAKYAN (7 titik): Si Ibarra ay sakay ng _____ papuntang libingan.', 'answer' => 'KARWAHE'],
                ['question' => 'TAO (12 titik): Sino ang nag-utos na sunugin ang bangkay ni Don Rafael?', 'answer' => 'PADRE GARROTE'],
                ['question' => 'TAO (6 titik): Sino ang dumating sa libingan na lulan ng karwahe?', 'answer' => 'IBARRA'],
                ['question' => 'LUGAR (4 titik): Saan itinapon ng tagapaglibing ang bangkay?', 'answer' => 'LAWA'],
                ['question' => 'AKSYON (10 titik): Ano ang ginawa ni Ibarra kay Padre Salvi?', 'answer' => 'DINALUHONG'],
                ['question' => 'TAO (11 titik): Sino ang nakita ni Ibarra na naka-sombrero at may baston na may puluhang garing?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (6 titik): Sino ang umalis na parang baliw sa libingan?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (6 titik): Sino ang kasunod ni Ibarra sa kanyang pag-alis?', 'answer' => 'MATANDA'],
                ['question' => 'LUGAR (14 titik): Saan papunta si Ibarra matapos umalis sa libingan?', 'answer' => 'PALABAS NG BAYAN'],
                ['question' => 'TAO (13 titik): Sino ang nangakong magpapagawa ng nitso?', 'answer' => 'KAPITAN TIAGO'],
            ],
            14 => [
                ['question' => 'TAO (16 titik): Ang matandang lalaki na palibot-libot sa lansangan ay si _____.', 'answer' => 'PILOSOPONG TASYO'],
                ['question' => 'KATANGIAN (11 titik): Ano ang dahilan kung bakit pinatigil si Mang Tasyo ng kanyang ina sa pag-aaral?', 'answer' => 'KATALINUHAN'],
                ['question' => 'BAGAY (8 titik): Ano ang napabayaan ni Pilosopo Tasyo dahil sa pagbabasa?', 'answer' => 'KAYAMANAN'],
                ['question' => 'LUGAR (8 titik): Saan nagtungo si Pilosopo Tasyo?', 'answer' => 'SIMBAHAN'],
                ['question' => 'TAO (14 titik): Sino ang ayaw magpaalis sa dalawang batang sakristan?', 'answer' => 'SAKRISTAN MAYOR'],
                ['question' => 'LUGAR (10 titik): Saan patungo ang magkapatid upang dupikalin ang kampana?', 'answer' => 'KAMPANARYO'],
                ['question' => 'GAWAIN (8 titik): Ano ang pinili ni Mang Tasyo kaysa magpari?', 'answer' => 'MAGASAWA'],
                ['question' => 'GAWAIN (9 titik): Ano ang itinuring niyang libangan matapos maulila?', 'answer' => 'PAGBABASA'],
                ['question' => 'LUGAR (9 titik): Saan nagtungo si Pilosopong Tasyo matapos lumabas ng simbahan?', 'answer' => 'KABAYANAN'],
                ['question' => 'AKSYON (13 titik): Paano tumugon si Pilosopong Tasyo sa balita tungkol kay Ibarra?', 'answer' => 'NAGKBITBALIKAT'],
            ],
            15 => [
                ['question' => 'TAO (7 titik): Si _____ ang mas matatakutin sa magkapatid.', 'answer' => 'CRISPIN'],
                ['question' => 'BILANG (10 titik): Magkano ang sinasahod ni Basilio sa pagpapatunog ng kampana?', 'answer' => 'DALAWANG PISO'],
                ['question' => 'BILANG (5 titik): Ilang beses nang minultahan ng Sakristan Mayor si Basilio?', 'answer' => 'TATLO'],
                ['question' => 'KASALANAN (7 titik): Ano ang ibinibintang ng Sakristan Mayor kay Crispin?', 'answer' => 'MAGNAKAW'],
                ['question' => 'PARUSA (4 titik): Paano raw siya papatayin ng kura kung hindi mailalabas ang ninakaw?', 'answer' => 'PALO'],
                ['question' => 'UGALI (7 titik): Anong ugali mayroon ang Sakristan Mayor?', 'answer' => 'MANUBOK'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Basilio nang siya ay pinagmulta?', 'answer' => 'TUMUTOL'],
                ['question' => 'AKSYON (9 titik): Anong ginawa ng Sakristan Mayor kay Crispin?', 'answer' => 'KINALADKAD'],
                ['question' => 'TUNOG (9 titik): Ano ang napalitan ng kalabog ng katawan ni Crispin?', 'answer' => 'ALINGAWNGAW'],
                ['question' => 'DAMDAMIN (4 titik): Ano ang naramdaman ni Basilio sa nangyari sa kanyang kapatid?', 'answer' => 'POOT'],
            ],
            16 => [
                ['question' => 'TAO (4 titik): Si _____ ang ina nina Basilio at Crispin.', 'answer' => 'SISA'],
                ['question' => 'AKSYON (10 titik): Ano ang ginagawa sa kanya ng asawa tuwing nauubos ang pansugal nito?', 'answer' => 'SINASAKTAN'],
                ['question' => 'GAWAIN (11 titik): Saan nilulustay ng asawa ni Sisa ang kanyang alahas?', 'answer' => 'PAGSUSUGAL'],
                ['question' => 'TAO (9 titik): Kanino nanghingi ng pindang na usa si Sisa?', 'answer' => 'MANG TASYO'],
                ['question' => 'LUGAR (7 titik): Saan pumitas ng kamatis si Sisa?', 'answer' => 'BAKURAN'],
                ['question' => 'TAO (5 titik): Sino ang hindi inaasahang dumating at umubos ng pagkain?', 'answer' => 'ASAWA'],
                ['question' => 'TAO (7 titik): Sino ang naalala ni Sisa nang makita niya ang asong itim?', 'answer' => 'CRISPIN'],
                ['question' => 'HAYOP (3 titik): Anong hayop ang nagdulot ng malungkot na pangitain kay Sisa?', 'answer' => 'ASO'],
                ['question' => 'PAGKAIN (9 titik): Anong ulam ang binili ni Sisa na idaragdag para sa mga anak?', 'answer' => 'ISDANG TUYO'],
                ['question' => 'BILANG (4 titik): Magkano ang ibinilin na ipatira ng asawa ni Sisa kay Basilio?', 'answer' => 'PISO'],
            ],
            17 => [
                ['question' => 'TAO (7 titik): Si _____ ang kumatok sa pinto ng bahay ni Sisa.', 'answer' => 'BASILIO'],
                ['question' => 'BAGAY (4 titik): Ano ang nakita ni Sisa na umaagos sa noo ni Basilio?', 'answer' => 'DUGO'],
                ['question' => 'TAO (7 titik): Sino ang naiwan sa kumbento?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (5 titik): Ano ang ginamit ni Basilio para makatakas sa kumbento?', 'answer' => 'LUBID'],
                ['question' => 'SALITA (9 titik): Ano ang isinisigaw ng mga kawal na narinig ni Basilio?', 'answer' => 'QUIEN VIVE'],
                ['question' => 'BAGAY (11 titik): Ano ang ibinibintang kay Crispin na kanyang ninakaw?', 'answer' => 'ONSA NG GINTO'],
                ['question' => 'AKSYON (8 titik): Nang mabalitaan ni Basilio na dumating ang kanyang ama, ano ang ginawa niya?', 'answer' => 'SINIYASAT'],
                ['question' => 'TAO (7 titik): Sino ang napanaginipan ni Basilio na pinapalo ng kura?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (11 titik): Ano ang nais kunin ni Basilio upang ipagbili?', 'answer' => 'BUNGANGKAHOY'],
                ['question' => 'BAGAY (4 titik): Ano ang nais gamitin ni Basilio upang manghuli ng ibon?', 'answer' => 'SILO'],
            ],
            18 => [
                ['question' => 'KATANGIAN (8 titik): Napansin ng mga tao na si Padre Salvi ay _____ pagkatapos ng misa.', 'answer' => 'MATAMLAY'],
                ['question' => 'TAO (11 titik): Sino ang nagpasimula ng usapan tungkol sa plenarya?', 'answer' => 'MANANG JUANA'],
                ['question' => 'BILANG (3 titik): Ilang plenarya ang sapat para makahango ng kaluluwa ayon kay Manang Rufa?', 'answer' => 'ISA'],
                ['question' => 'TAO (4 titik): Sino ang dumating na may sunong na bakol?', 'answer' => 'SISA'],
                ['question' => 'BAGAY (5 titik): Ano ang sunong ni Sisa pagpasok sa kumbento?', 'answer' => 'BAKOL'],
                ['question' => 'DAMDAMIN (10 titik): Ano ang naramdaman ni Sisa habang paakyat ng hagdanan?', 'answer' => 'KINAKABAHAN'],
                ['question' => 'UGALI (9 titik): Ano ang ipinakitang pakikitungo ng tagapagluto kay Sisa?', 'answer' => 'PANLALAMIG'],
                ['question' => 'BAGAY (12 titik): Ano ang laman ng bakol na dala ni Sisa?', 'answer' => 'SARIWANG GULAY'],
                ['question' => 'TAO (3 titik): Sino ang nais makausap ni Sisa?', 'answer' => 'PARI'],
                ['question' => 'AKSYON (6 titik): Paano iniayos ni Sisa ang dalang sariwang gulay?', 'answer' => 'MAINGAT'],
            ],
            19 => [
                ['question' => 'TAO (4 titik): Si Ibarra ay nagmamasid sa lawa kasama ang _____.', 'answer' => 'GURO'],
                ['question' => 'LUGAR (4 titik): Saan itinapon ang bangkay ng ama ni Ibarra?', 'answer' => 'LAWA'],
                ['question' => 'TAO (14 titik): Sino ang kasama ng guro sa libing ni Don Rafael?', 'answer' => 'TENYENTE GUEVARRA'],
                ['question' => 'KATANGIAN (15 titik): Ayon sa guro, ito ay tulad ng mabuting bagay ngunit hindi nagtatagal.', 'answer' => 'KAGANDAHANGLOOB'],
                ['question' => 'GAWAIN (13 titik): Ano ang kailangang gawin nina Ibarra upang mapabuti ang pagtuturo?', 'answer' => 'PAGTUTULUNGAN'],
                ['question' => 'TAO (7 titik): Sino ang kailangang mabigyan ng pagganyak upang matuto?', 'answer' => 'KABATAAN'],
                ['question' => 'GAWAIN (9 titik): Ang mga bata ay nasanay sa _____ kaya\'t hindi nila nauunawaan ang binabasa.', 'answer' => 'PAGSASAULO'],
                ['question' => 'TAO (12 titik): Sino ang nagpatawag sa guro sa pamamagitan ng Sakristan Mayor?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Padre Damaso sa guro dahil sa paggamit ng wikang Kastila?', 'answer' => 'KINUTYA'],
                ['question' => 'GAWAIN (8 titik): Ano ang natuklasan ng guro na hindi nakatutulong sa mga bata?', 'answer' => 'PAMAMALO'],
            ],
            20 => [
                ['question' => 'TAO (10 titik): Si _____ ang pinuno ng liberal.', 'answer' => 'DON FILIPO'],
                ['question' => 'BILANG (6 titik): Ilang pangkat ang kasali sa pagpupulong?', 'answer' => 'DALAWA'],
                ['question' => 'GRUPO (11 titik): Ito ang pangkat ng mga matatanda.', 'answer' => 'CONSERBADOR'],
                ['question' => 'GRUPO (7 titik): Ito ay binubuo ng mga kabataan.', 'answer' => 'LIBERAL'],
                ['question' => 'TAO (7 titik): Sino ang pumunta sa tribunal na mainit ang ulo?', 'answer' => 'KAPITAN'],
                ['question' => 'TAO (4 titik): Sino ang kasama ni Ibarra sa pagpunta sa tribunal?', 'answer' => 'GURO'],
                ['question' => 'TAO (14 titik): Sino ang Kapitan na naging kalaban ni Don Rafael?', 'answer' => 'KAPITAN BASILIO'],
                ['question' => 'OKASYON (10 titik): Ano ang pinaghahandaan ng dalawang pangkat?', 'answer' => 'KAPISTAHAN'],
                ['question' => 'TAO (3 titik): Sino ang nagnanais ng komedya sa kapistahan?', 'answer' => 'KURA'],
                ['question' => 'TAO (12 titik): Nang maging matiwasay ang pulong, sino ang humingi ng pahintulot upang magsalita?', 'answer' => 'BATANG KABESA'],
            ],
            21 => [
                ['question' => 'DAMDAMIN (5 titik): Si Sisa ay nakaramdam ng _____ nang makita ang dalawang guwardiya sibil.', 'answer' => 'TAKOT'],
                ['question' => 'TAO (7 titik): Sino ang hinahanap ng mga guwardiya sibil?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (8 titik): Ano ang itinakip ni Sisa sa mukha upang hindi siya makilala?', 'answer' => 'PAMINDONG'],
                ['question' => 'TAO (4 titik): Sino ang nakakulong sa kuwartel?', 'answer' => 'SISA'],
                ['question' => 'TAO (3 titik): Sino ang dahilan ng pagkakakulong ni Sisa?', 'answer' => 'KURA'],
                ['question' => 'LUGAR (8 titik): Saan nakakulong si Sisa?', 'answer' => 'KUWARTEL'],
                ['question' => 'AKSYON (8 titik): Ano ang ginawa ng mga guwardiya kay Sisa?', 'answer' => 'IKINULONG'],
                ['question' => 'TAO (7 titik): Sino ang nagsabi kay Sisa na gawa ng kura ang kanyang pagkakakulong?', 'answer' => 'ALPERES'],
                ['question' => 'KALAGAYAN (7 titik): Ano ang nangyari kay Sisa pagkatapos makulong?', 'answer' => 'NABALIW'],
                ['question' => 'TAO (7 titik): Ang pilas ng baro na nakita ni Sisa ay pag-aari ni _____.', 'answer' => 'BASILIO'],
            ],
            22 => [
                ['question' => 'TAO (11 titik): Sino ang madalas magkamali sa pagmimisa at laging natitigilan?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (17 titik): Sino ang binatang dumating at bumati kay Padre Salvi?', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'TAO (11 titik): Sino ang ayaw maanyayahan sa salu-salo?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (17 titik): Sino ang nag-imbita kay Padre Salvi?', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'LUGAR (5 titik): Saan gaganapin ang salu-salo?', 'answer' => 'BATIS'],
                ['question' => 'TAO (10 titik): Sino ang sumalubong kay Ibarra sa daanan?', 'answer' => 'ISANG LALAKI'],
                ['question' => 'GAWAIN (5 titik): Ano ang nais ng lalaki kay Ibarra?', 'answer' => 'TULONG'],
                ['question' => 'BILANG (5 titik): Ilang araw ang naging paghahanda sa kapistahan?', 'answer' => 'TATLO'],
                ['question' => 'KATANGIAN (10 titik): Ano ang napuna nila kay Padre Salvi na dahilan ng pagpayat?', 'answer' => 'GANANG KUMAIN'],
                ['question' => 'TAO (6 titik): Kaninong bahay tumuloy si Ibarra?', 'answer' => 'KATIPAN'],
            ],
            23 => [
                ['question' => 'TAO (5 titik): Sino ang pinsan ni Maria Clara na masiyahin?', 'answer' => 'SINANG'],
                ['question' => 'TAO (8 titik): Sino sa mga kaibigan ni Maria Clara ang laging walang imik?', 'answer' => 'VICTORIA'],
                ['question' => 'TAO (6 titik): Sino sa mga kaibigan ni Maria Clara ang maganda at palaisip?', 'answer' => 'NENENG'],
                ['question' => 'BAGAY (6 titik): Ano ang nadatnan nila sa tabi ng lawa?', 'answer' => 'BANGKA'],
                ['question' => 'TAO (8 titik): Sino ang binatang may matikas na anyo at matipunong katawan?', 'answer' => 'BANGKERO'],
                ['question' => 'TAO (13 titik): Kaninong baklad tumuloy sina Maria Clara at Ibarra?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'BAGAY (4 titik): Ano ang ginamit ni Maria Clara sa pag-awit?', 'answer' => 'ALPA'],
                ['question' => 'HAYOP (6 titik): Ano ang nahuli ng baklad?', 'answer' => 'BUWAYA'],
                ['question' => 'BAGAY (6 titik): Ano ang kinuha ni Ibarra upang tulungan ang bangkero?', 'answer' => 'PUNYAL'],
                ['question' => 'TAO (6 titik): Sino ang nagmamay-ari ng baybayin ng gubat?', 'answer' => 'IBARRA'],
            ],
            24 => [
                ['question' => 'TAO (11 titik): Sino ang nagtungo sa gubat?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TUNOG (10 titik): Ano ang narinig ni Padre Salvi sa may batisan?', 'answer' => 'HALAKHAKAN'],
                ['question' => 'LUGAR (11 titik): Saan kumubli si Padre Salvi nang marinig ang halakhakan?', 'answer' => 'PUNONGKAHOY'],
                ['question' => 'TAO (19 titik): Sino ang babaeng payat at marusing na sumipot sa piging?', 'answer' => 'SISA'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Sisa pagkakita sa Alperes?', 'answer' => 'TUMAKBO'],
                ['question' => 'TAO (7 titik): Sino ang nakita ni Sisa kaya siya tumakbo?', 'answer' => 'ALPERES'],
                ['question' => 'BILANG (4 titik): Ilang araw nang nababaliw si Sisa?', 'answer' => 'APAT'],
                ['question' => 'AKLAT (16 titik): Ano ang binabasa ng mga kabinataan?', 'answer' => 'GULONG NG KAPALARAN'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Padre sa aklat na iyon?', 'answer' => 'PINUNIT'],
                ['question' => 'TAO (5 titik): Sino ang tinutukoy ng guwardiya sibil bilang piloto at masamang tao?', 'answer' => 'ELIAS'],
            ],
            25 => [
                ['question' => 'TAO (13 titik): Si Ibarra ay nagtungo sa bahay ni _____.', 'answer' => 'PILOSOPO TASYO'],
                ['question' => 'GAWAIN (10 titik): Ano ang nadatnan niyang ginagawa ng matanda?', 'answer' => 'NAGSUSULAT'],
                ['question' => 'BAGAY (8 titik): Ano ang pangarap ni Ibarra?', 'answer' => 'PAARALAN'],
                ['question' => 'INSTITUSIYON (10 titik): Ayon kay Mang Tasyo, ito ay kasangkapan lamang ng simbahan.', 'answer' => 'PAMAHALAAN'],
                ['question' => 'TAO (10 titik): Sino ang nagunita ni Ibarra habang tinutupad ang kanyang balak?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (7 titik): Saan nanggaling si Ibarra bago magtungo kay Mang Tasyo?', 'answer' => 'BUKIRIN'],
                ['question' => 'BAGAY (10 titik): Ano ang kinuha ni Ibarra sa kanyang kalupi?', 'answer' => 'ILANG PAPEL'],
                ['question' => 'TAO (13 titik): Sino rin ang may pangarap na makapagtayo ng paaralan?', 'answer' => 'PILOSOPO TASYO'],
                ['question' => 'AKSYON (4 titik): Ano ang sadya ni Ibarra kay Mang Tasyo?', 'answer' => 'PAYO'],
                ['question' => 'HALIMBAWA (11 titik): Saan inihalintulad ni Mang Tasyo sina Ibarra?', 'answer' => 'PUNONG GUBAT'],
            ],
                        26 => [
                ['question' => 'BUWAN (9 titik): Anong buwan ipinagdiriwang ang pista sa bayan ng San Diego?', 'answer' => 'NOBYEMBRE'],
                ['question' => 'BAGAY (9 titik): Ano ang itinayo sa masayang lansangan ng San Diego?', 'answer' => 'SINGKABAN'],
                ['question' => 'BAGAY (9 titik): Ang _____ ay idaraos sa malaking tolda na tinutukuran ng kawayan.', 'answer' => 'PRUSISYON'],
                ['question' => 'BAGAY (15 titik): Ano ang gaganapin sa itinayong malaking entablado sa liwasan ng bayan?', 'answer' => 'KOMEDYA NG TONDO'],
                ['question' => 'TAO (12 titik): Sino ang napiling magsermon sa umaga?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (14 titik): Sino sa mga kilalang tahur ang may dalang 18,000 piso?', 'answer' => 'KAPITAN JOAQUIN'],
                ['question' => 'TAO (8 titik): Sino ang paulit-ulit na nagbabalita tungkol sa pagpapatayo ng bahay-paaralan?', 'answer' => 'NYOR JUAN'],
                ['question' => 'TAO (6 titik): Sino sa mga kilalang tahur ang Tsino na may puhunan na sampung libo?', 'answer' => 'CARLOS'],
                ['question' => 'TAO (13 titik): Sino sa mga kilalang tahur ang mambabangka?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (8 titik): Sino ang napiling magsermon sa gabi?', 'answer' => 'BANGKERO'],
            ],
            27 => [
                ['question' => 'BAGAY (6 titik): Ano ang pasalubong para kay Maria Clara mula Europa?', 'answer' => 'PIYANO'],
                ['question' => 'DAMDAMIN (5 titik): Ano ang naramdaman ni Maria Clara nang makita niya ang lalaking ketongin?', 'answer' => 'NAAWA'],
                ['question' => 'AKSYON (10 titik): Si Sisa ay _____ ng mga guwardiya sibil.', 'answer' => 'KINALADKAD'],
                ['question' => 'TAO (11 titik): Sino ang nag-ayang umuwi dahil nawala na ang kasayahan?', 'answer' => 'MARIA CLARA'],
                ['question' => 'BAGAY (5 titik): Ano ang ibinigay ni Maria Clara sa lalaking ketongin?', 'answer' => 'AGNOS'],
                ['question' => 'GAWAIN (8 titik): Saan inanyayahan ng kaniyang mga kaibigan si Maria Clara?', 'answer' => 'MAMASYAL'],
                ['question' => 'LUGAR (9 titik): Saan naparaan ang grupo ni Maria Clara?', 'answer' => 'PANULUKAN'],
                ['question' => 'BAGAY (9 titik): Alin sa mga pasalubong ni Ibarra ang may mga brilyante at esmeralda?', 'answer' => 'RELIKARYO'],
                ['question' => 'TAO (8 titik): Ano ang idinahilan ni Ibarra na darating nang anyayahan siya ni Kapitan Tiago na maghapunan?', 'answer' => 'PANAUHIN'],
                ['question' => 'TAO (4 titik): Sino ang lumapit at tumangan sa bisig ng ketongin?', 'answer' => 'SISA'],
            ],
            28 => [
                ['question' => 'LUGAR (7 titik): Saan itinayo ang malaking entablado para sa mga dulang Kastila?', 'answer' => 'LIWASAN'],
                ['question' => 'TAO (9 titik): Sino ang hindi nakadalo sa pagbabasbas ng panukalang bato ng paaralan?', 'answer' => 'G. IBARRA'],
                ['question' => 'KATANGIAN (10 titik): Dahil sa _____, hindi nakadalo si G. Ibarra sa pagbabasbas.', 'answer' => 'KARAMDAMAN'],
                ['question' => 'BAGAY (9 titik): Ano ang sinimulan noong ika-11 ng umaga at iniligid sa simbahan?', 'answer' => 'PRUSISYON'],
                ['question' => 'BAGAY (16 titik): Anong musika ang tinugtog ng mga mayayamang anak sa piyano?', 'answer' => 'ALEMAN AT ITALYANO'],
                ['question' => 'TAO (12 titik): Sino ang nagbigay ng sermon sa misa kantada?', 'answer' => 'PADRE MANUEL'],
                ['question' => 'BAGAY (15 titik): Anong uri ng komedya ang kinagiliwan ng mga Indio?', 'answer' => 'KOMEDYANG TAGALOG'],
                ['question' => 'TAO (12 titik): Sino ang kabilang sa mga panauhin ni Kapitan Tiago bukod kina Padre Salvi at Sibyla?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (9 titik): Saan ipinagdiriwang ang pista na pinamumunuan ng mga Pransiskano?', 'answer' => 'SAN DIEGO'],
                ['question' => 'TAO (6 titik): Ang _____ ang dumating kinahapunan at naanyayahan sa paglalagay ng unang bato.', 'answer' => 'ALKALDE'],
            ],
            29 => [
                ['question' => 'BAGAY (6 titik): Ano ang inasahang magdadala ng higit na kasayahan?', 'answer' => 'MUSIKO'],
                ['question' => 'BAGAY (4 titik): Ano ang ginamit ng mamamayan kasama ang kanilang alahas?', 'answer' => 'BAUL'],
                ['question' => 'DAMDAMIN (8 titik): Ang lalaking may sombrero ay nagpapahiwatig ng _____.', 'answer' => 'MALUNGKOT'],
                ['question' => 'TAO (5 titik): Sino ang tanging lalaking hindi nagpalit ng kasuotan?', 'answer' => 'TASIO'],
                ['question' => 'GAWAIN (11 titik): Saan ibinabatay ng lalaking may sombrero ang kanyang pangangampanya?', 'answer' => 'PAGSASAGAWA'],
                ['question' => 'GAWAIN (7 titik): Ano ang hinamon ng militar sa kanya kung ayaw niya sa sitwasyon?', 'answer' => 'MAGBITIW'],
                ['question' => 'BAGAY (6 titik): Ano ang turing ng lalaking may sumbrero sa tungkulin?', 'answer' => 'PASANIN'],
                ['question' => 'BILANG (6 titik): Ilang banda ng musiko ang nahati sa harap ng simbahan?', 'answer' => 'DALAWA'],
                ['question' => 'ORAS (7 titik): Kailan nagsimula ang prusisyon?', 'answer' => 'IKAWALO'],
                ['question' => 'TAO (6 titik): Sino ang kasama ni San Diego de Alcala sa prusisyon?', 'answer' => 'BIRHEN'],
            ],
            30 => [
                ['question' => 'BAGAY (11 titik): Ano ang dinudumog ng mga tao upang makalapit?', 'answer' => 'AGWA BENDITA'],
                ['question' => 'KATANGIAN (9 titik): Anong uri ng amoy ang nasa simbahan?', 'answer' => 'MASANGSANG'],
                ['question' => 'LUGAR (5 titik): Saan nakapuwesto si Ibarra?', 'answer' => 'SULOK'],
                ['question' => 'LUGAR (10 titik): Malapit sa _____ ang reserved seat ni Maria Clara.', 'answer' => 'ALTAR MAYOR'],
                ['question' => 'TAO (6 titik): Sino ang dumating na kasama ang kagawad?', 'answer' => 'ALKALDE'],
                ['question' => 'BILANG (4 titik): Ilang medalya ang suot ng Alkalde?', 'answer' => 'LIMA'],
                ['question' => 'BAGAY (10 titik): Ano ang narinig bukod sa koro bago magsimula ang misa?', 'answer' => 'KAMPANILYA'],
                ['question' => 'TAO (12 titik): Sino ang nagbigay ng sermon?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (5 titik): Saan daw pupunta ang mga kaluluwa ng nakikinig sa sermon?', 'answer' => 'LANGIT'],
                ['question' => 'HALAGA (8 titik): Magkano ang ibabayad ng bayan sa sermon, kung kaya\'t kailangan nilang marinig iyon?', 'answer' => '250 PISO'],
            ],
            31 => [
                ['question' => 'WIKA (7 titik): Ano ang wika ng sermon na nauunawaan lamang ng mga guwardiya sibil, tulisan, at mga banal?', 'answer' => 'KASTILA'],
                ['question' => 'BAGAY (6 titik): Ano ang inihalintulad sa katangian ni San Diego na kasing liwanag ng araw?', 'answer' => 'BITUIN'],
                ['question' => 'GAWAIN (8 titik): Sa anong paksa ni Padre Damaso hinamon niya ang mga Indio sa huling bahagi ng sermon?', 'answer' => 'PANLALAIT'],
                ['question' => 'GAWAIN (11 titik): Ano ang maikling pagbati ng mga mayayabang na estudyante sa pari?', 'answer' => 'MAGANDANG ARAW'],
                ['question' => 'KATANGIAN (6 titik): Ano ang parusa sa mga eskumulgado o hindi sumasampalataya na uulanin sa dilubyo?', 'answer' => 'PALALO'],
                ['question' => 'BAGAY (8 titik): Ano ang tawag sa sermon ni Padre Damaso patungkol kay Ibarra?', 'answer' => 'PARUNGGIT'],
                ['question' => 'KATANGIAN (11 titik): Ano ang tawag sa mga nag-aaway at nagmumurahan sa simbahan?', 'answer' => 'WALANG GALANG'],
                ['question' => 'KATANGIAN (8 titik): Ano ang bunga ng bagong panahon?', 'answer' => 'KALASWAAN'],
                ['question' => 'BAGAY (5 titik): Ano ang nakasalalay ayon sa binalita kay Ibarra?', 'answer' => 'BUHAY'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ng lalaking may sombrero nang lumapit kay Ibarra?', 'answer' => 'BUMULONG'],
            ],
            32 => [
                ['question' => 'BAGAY (7 titik): Anong malaking bagay ang itatayo sa lugar na kinaroroonan, ayon kay Ibarra?', 'answer' => 'PAARALAN'],
                ['question' => 'TAO (5 titik): Sino ang lumapit at nagpakita ng ngiti kay Ibarra upang ipaalam ang kaniyang bilin?', 'answer' => 'ELIAS'],
                ['question' => 'KATANGIAN (5 titik): Anong kulay ang damit ng taong madilaw na siyang naghanda ng kasangkapang panghugos?', 'answer' => 'DILAW'],
                ['question' => 'TAO (11 titik): Sino ang bumasang may nagniningning na tinig ng mga nakasulat sa bumbong?', 'answer' => 'PADRE SALVI'],
                ['question' => 'BAGAY (9 titik): Ano ang ipinaloob sa kahang kristal kasama ang medalya at iba pa?', 'answer' => 'KASULATAN'],
                ['question' => 'BAGAY (7 titik): Ano ang inilagay ng Alkalde sa hukay bago sinundan ng kura?', 'answer' => 'SEMENTO'],
                ['question' => 'TAO (6 titik): Sa pagdiriwang, sino ang sinundan ng kura sa pagbaba sa hukay habang sinulyapan ang nakabiting bato?', 'answer' => 'IBARRA'],
                ['question' => 'BAGAY (13 titik): Ano ang dala ni Ibarra na gawa sa bakal?', 'answer' => 'KUTSARANG BAKAL'],
                ['question' => 'BAGAY (6 titik): Ano ang tawag sa nasawi o natabunan ng bato?', 'answer' => 'BANGKAY'],
                ['question' => 'BAGAY (4 titik): Ano ang tawag sa makinaryang ginagamit sa pagtaas at pagbaba ng mabibigat na bagay?', 'answer' => 'KALO'],
            ],
        ];

        foreach ($kabanatas as $kabanataId => $items) {
            foreach ($items as $item) {
                GuessWord::create([
                    'kabanata_id' => $kabanataId,
                    'question'    => $item['question'],
                    'answer'      => strtoupper($item['answer']),
                    'pickedChar'  => '',
                ]);
            }
        }
    }
}
