<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GuessWord;

class GuessWordSeeder extends Seeder
{
    public function run(): void
    {
        $kabanatas = [
            1 => [
                ['question' => 'TAO (11 titik): Siya ang naging kura paroko ng San Diego sa loob ng dalawampung taon.', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TITULO/POSISYON (7 titik): Siya ang kinikilalang kinatawan ng hari sa Pilipinas.', 'answer' => 'HENERAL'],
                ['question' => 'TAO (11 titik): Siya ang paring nag awat sa pagtatalo ng tenyente at ni Padre Damaso.', 'answer' => 'PADRE SIBYLA'],
                ['question' => 'LUGAR (7 titik): Saang pook nakatirik ang bahay ni Kapitan Tiago.', 'answer' => 'BINUNDOK'],
                ['question' => 'PANAHON/TAGAL (9 titik): Gaano katagal nanungkulan si Padre Damaso sa San Diego.', 'answer' => 'DALAWAMPU'],
                ['question' => 'PANINIWALA/DESKRIPSYON (11 titik): Ayon sa kanya, ang mga Indio raw ay likas na ___.', 'answer' => 'MAPAGPABAYA'],
                ['question' => 'TAO, MAY INISYAL (7 titik): Siya ang nagpahayag na ang mga Indio ay mangmang at walang malasakit.', 'answer' => 'G LARUJA'],
                ['question' => 'TAO (14 titik): Siya ang mapagpanggap na asawa ni Dr. de Espadana.', 'answer' => 'DONYA VICTORINA'],
                ['question' => 'KAISIPAN/KAUGALIANG FILIPINO (11 titik): Ayon kay G. Laruja, kulang daw ang mga Indio sa ______.', 'answer' => 'UTANG NA LOOB'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang nadama ni Padre Damaso hanggang muntik mabitawan ang hawak na kopita.', 'answer' => 'NABIGLA'],
            ],
            2 => [
                ['question' => 'TAO (18 titik): Siya ang binatang bagong balik mula sa pag-aaral sa Europa.', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'PANAHON/TAGAL (4 titik): Ilang taon nanatili si Ibarra sa Europa para mag-aral.', 'answer' => 'PITO'],
                ['question' => 'TAO (13 titik): Siya ang matalik na kakilala ng ama ni Ibarra na nag-imbita ng pananghalian.', 'answer' => 'KAPITAN TINONG'],
                ['question' => 'TAO (12 titik): Siya ang nagpakilala kay Ibarra sa salusalo.', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (11 titik): Siya ang ama ni Crisostomo Ibarra.', 'answer' => 'DON RAFAEL'],
                ['question' => 'GRUPO (6 titik): Kaninong umpukan lumapit si Ibarra upang makipagkilala.', 'answer' => 'BINATA'],
                ['question' => 'TAO (11 titik): Sino ang kanyang nakilala sa umpukan.', 'answer' => 'ISANG MAKATA'],
                ['question' => 'BAGAY/SINING (4 titik): Ano ang muling nagpaalab ng pagmamahal ni Ibarra sa bayan habang kausap ang makata.', 'answer' => 'TULA'],
                ['question' => 'LUGAR (8 titik): Tinanggihan ni Ibarra ang alok na pananghalian dahil siya ay uuwi na sa ______.', 'answer' => 'SAN DIEGO'],
                ['question' => 'PANGALAN (8 titik): Juan Crisostomo Ibarra y ____________, ang buong pangalan ni Ibarra.', 'answer' => 'MAGSALIN'],
            ],
            3 => [
                ['question' => 'PAGKAIN (6 titik): Anong ulam ang inihanda ni Kapitan Tiago sa salusalo?', 'answer' => 'TINOLA'],
                ['question' => 'ALAALA (8 titik): Ano ang nagbalik ng gunita kay Ibarra nang maalala ang sinabi ng kanyang dating kura?', 'answer' => 'KABATAAN'],
                ['question' => 'BAGAY (9 titik): Ano ang tinukoy tungkol sa "luklukan" o upuan sa larawan?', 'answer' => 'KOMPESOR'],
                ['question' => 'BAGAY (8 titik): Ano ang pinag-aagawan nina Padre Damaso at Padre Sibyla?', 'answer' => 'KABISERA'],
                ['question' => 'LUGAR (6 titik): Saang pook namalagi si Ibarra bago siya bumalik sa bayan?', 'answer' => 'EUROPA'],
                ['question' => 'BANSA (7 titik): Itinuturing ni Ibarra na pangalawang inang bayan.', 'answer' => 'ESPANYA'],
                ['question' => 'PAGKAIN (12 titik): Anong bahagi ng manok ang napunta kay Padre Damaso kaya\'t binagsak niya ang kutsara\'t tinulak ang pinggan?', 'answer' => 'LEEG AT PAKPAK'],
                ['question' => 'KATANGIAN (11 titik): Ayon kay Padre Damaso, ano ang kasamaan na dulot ng pagpapaaral sa Europa?', 'answer' => 'MAPAGMATAAS'],
                ['question' => 'BAGAY (9 titik): Sa kanilang pagtatalo, ano ang sinabi ni Padre Sibyla na dapat mapunta kay Padre Damaso?', 'answer' => 'LUKLUKAN'],
                ['question' => 'ARALIN (10 titik): Ano ang unang pinag-aralan ni Ibarra bago siya tumungo sa isang bayan?', 'answer' => 'KASAYSAYAN'],
            ],
            4 => [
                ['question' => 'TAO (6 titik): Sino ang inilalarawan na naglalakad at walang tiyak na patutunguhan?', 'answer' => 'IBARRA'],
                ['question' => 'LUGAR (8 titik): Saan nakarating si Ibarra habang siya\'y naglalakad?', 'answer' => 'BINUNDOK'],
                ['question' => 'TAO (11 titik): Sino ang pinasasaringan ni Padre Damaso sa kanyang sermon?', 'answer' => 'DON RAFAEL'],
                ['question' => 'LUGAR (7 titik): Saan pinasasaringan ni Padre Damaso ang ama ni Ibarra?', 'answer' => 'PULPITO'],
                ['question' => 'KATANGIAN (11 titik): Saan nakilala ang dating artilyero na natanggal sa pagiging sundalo?', 'answer' => 'KAMANGMANGAN'],
                ['question' => 'PARATANG (11 titik): Ano ang ibinintang sa ama ni Ibarra?', 'answer' => 'PILIBUSTERO'],
                ['question' => 'TAO (9 titik): Siya ang sumuka ng dugo at kalaunan ay namatay.', 'answer' => 'ARTILYERO'],
                ['question' => 'PARATANG (12 titik): Ano pa ang isinakdal sa ama ni Ibarra bukod sa pagiging pilibustero?', 'answer' => 'NANGAMKAM'],
                ['question' => 'LUGAR (12 titik): Saan nagpahatid si Ibarra matapos ang usapan nila ng tenyente?', 'answer' => 'FONDA DE LALA'],
                ['question' => 'SASAKYAN (6 titik): Ano ang sinakyan ni Ibarra papuntang Fonda de Lala?', 'answer' => 'KALESA'],
            ],
            5 => [
                ['question' => 'DAMDAMIN (13 titik): Ano ang naramdaman ni Ibarra nang siya\'y umupo sa isang silyon?', 'answer' => 'BALISANG-BALISA'],
                ['question' => 'PANGITAIN (14 titik): Sa pangitain ni Ibarra, sino ang binatang masayang nakita niya sa ibayong dagat?', 'answer' => 'KANYANG SARILI'],
                ['question' => 'BAHAGI NG SILID (10 titik): Saang bahagi ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?', 'answer' => 'DURUNGAWAN'],
                ['question' => 'TAO (11 titik): Sino ang magandang dilag na nakita ni Ibarra na nakadamit Pilipina?', 'answer' => 'MARIA CLARA'],
                ['question' => 'INSTRUMENTO (7 titik): Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra.', 'answer' => 'BIYULIN'],
                ['question' => 'TAO (11 titik): Sino ang palaging laman ng isip ni Ibarra?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (8 titik): Saan nagmula si Maria Clara?', 'answer' => 'BEATERYO'],
                ['question' => 'BILANG (6 titik): Ilan ang pangitain na nasilayan ni Ibarra sa kalawakan?', 'answer' => 'DALAWA'],
                ['question' => 'TAO (3 titik): Sa kanyang pangitain, sino ang lalaking nakita ni Ibarra na nagdurusa sa kulungan?', 'answer' => 'AMA'],
                ['question' => 'BAGAY (4 titik): Ano ang namatay sa katapat na bahay Ibarra?', 'answer' => 'ILAW'],
            ],
            6 => [
                ['question' => 'DAMDAMIN (13 titik): Ano ang naramdaman ni Ibarra nang siya\'y umupo sa isang silyon?', 'answer' => 'BALISANG-BALISA'],
                ['question' => 'PANGITAIN (14 titik): Sa pangitain ni Ibarra, sino ang binatang masayang nakita niya sa ibayong dagat?', 'answer' => 'KANYANG SARILI'],
                ['question' => 'BAHAGI NG SILID (10 titik): Saang bahagi ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?', 'answer' => 'DURUNGAWAN'],
                ['question' => 'TAO (11 titik): Sino ang magandang dilag na nakita ni Ibarra na nakadamit Pilipina?', 'answer' => 'MARIA CLARA'],
                ['question' => 'INSTRUMENTO (7 titik): Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra.', 'answer' => 'BIYULIN'],
                ['question' => 'TAO (11 titik): Sino ang palaging laman ng isip ni Ibarra?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (8 titik): Saan nagmula si Maria Clara?', 'answer' => 'BEATERYO'],
                ['question' => 'BILANG (6 titik): Ilan ang pangitain na nasilayan ni Ibarra sa kalawakan?', 'answer' => 'DALAWA'],
                ['question' => 'TAO (3 titik): Sa kanyang pangitain, sino ang lalaking nakita ni Ibarra na nagdurusa sa kulungan?', 'answer' => 'AMA'],
                ['question' => 'BAGAY (4 titik): Ano ang namatay sa katapat na bahay Ibarra?', 'answer' => 'ILAW'],
            ],
            7 => [
                ['question' => 'GAWAIN (8 titik): Si Maria Clara ay nagtatanggal ng inip sa pamamagitan ng _____.', 'answer' => 'PANANAHI'],
                ['question' => 'TAO (13 titik): Sino ang nagpayo kay Maria Clara na magbakasyon muna sa San Diego o Malabon?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'KATANGIAN (9 titik): Ano ang napansin ni Kapitan Tiago kay Maria Clara?', 'answer' => 'NAMUMUTLA'],
                ['question' => 'BAGAY (8 titik): Ano ang tumigil sa tapat ng bahay nina Maria Clara dahilan para mawalan siya ng kulay?', 'answer' => 'SASAKYAN'],
                ['question' => 'LUGAR (6 titik): Saang paaralan nag-aral si Ibarra nang siya ay bata pa?', 'answer' => 'ATENEO'],
                ['question' => 'WIKA (5 titik): Anong wika ang ginagamit ni Ibarra sa pagtuturo ng mga pangalan ng bulaklak?', 'answer' => 'LATIN'],
                ['question' => 'HALAMAN (4 titik): Anong uri ng bulaklak ang ginamit sa putong?', 'answer' => 'SUHA'],
                ['question' => 'PANGALAN (5 titik): Ano ang pangalan na itinawag ni Ibarra kay Maria Clara?', 'answer' => 'CHLOE'],
                ['question' => 'DAMDAMIN (5 titik): Ano ang naramdaman ni Ibarra nang siya ay tawanan ni Maria Clara?', 'answer' => 'TAMPO'],
                ['question' => 'HALAMAN (7 titik): Ang halamang inilagay sa loob ng sombrero ay _____.', 'answer' => 'SAMBONG'],
            ],
            8 => [
                ['question' => 'SASAKYAN (6 titik): Si Ibarra ay sakay ng _____ papunta sa Maynila.', 'answer' => 'KALESA'],
                ['question' => 'GAWAIN (10 titik): Ano ang ginagawa ng mga bilanggo sa larawan?', 'answer' => 'NAGPIPISON'],
                ['question' => 'AMOY (6 titik): Anong amoy ang nakapagpaalala kay Ibarra ng kanyang pagkahilo?', 'answer' => 'TABAKO'],
                ['question' => 'LUGAR (14 titik): Ano ang naalala ni Ibarra sa Europa na umaakit sa maraming tao?', 'answer' => 'HARDING BOTANIKO'],
                ['question' => 'LUGAR (6 titik): Ano ang nakita ni Ibarra na naliligid ng makakapal na pader?', 'answer' => 'MAYNILA'],
                ['question' => 'TAO (11 titik): Sino ang nagbigay ng bilin kay Ibarra bago siya umalis ng Europa?', 'answer' => 'GURONG PARI'],
                ['question' => 'BAGAY (5 titik): Ano ang sinadya ng mga banyaga sa bayan?', 'answer' => 'GINTO'],
                ['question' => 'TAO (13 titik): Sino ang naraanan ni Ibarra na nakatanikala at nagpipison ng bato?', 'answer' => 'ILANG BILANGGO'],
                ['question' => 'TAO (12 titik): Sino ang namataan ni Ibarra sa magandang karwahe na nakakunot-noo?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (10 titik): Ang punong talisay na nakita ni Ibarra ay sa lugar ng _____.', 'answer' => 'SAN GABRIEL'],
            ],
            9 => [
                ['question' => 'LUGAR (8 titik): Si Maria Clara ay nagtungo sa _____ upang kunin ang kanyang mga kagamitan.', 'answer' => 'BEATERYO'],
                ['question' => 'TAO (12 titik): Sino ang dumating at nagtanong kina Tiya Isabel at Maria Clara kung saan sila patungo?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (10 titik): Sino ang kasama ni Maria Clara sa karwahe?', 'answer' => 'TIYA ISABEL'],
                ['question' => 'TAO (12 titik): Sino ang nagtungo sa kumbento matapos magmisa?', 'answer' => 'PADRE SIBYLA'],
                ['question' => 'LUGAR (8 titik): Saang lugar nagtungo si Padre Sibyla pagkatapos ng misa?', 'answer' => 'KUMBENTO'],
                ['question' => 'TAO (6 titik): Sino ang mapapangasawa ni Maria Clara?', 'answer' => 'IBARRA'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang naramdaman ni Kapitan Tiago sa di-karaniwang anyo ni Padre Damaso?', 'answer' => 'NABAHALA'],
                ['question' => 'TAO (15 titik): Kanino nakarating ang nangyari, kaya\'t pinaalis si Padre Damaso?', 'answer' => 'KAPITAN HENERAL'],
                ['question' => 'BAGAY (12 titik): Ano ang pinatay ni Kapitan Tiago patungkol sa paglalakbay ni Ibarra?', 'answer' => 'ILAW AT KANDILA'],
                ['question' => 'TAO (11 titik): Kanino ibinilin ni Kapitan Tiago na itulos ang ilaw at kandila nang umalis si Ibarra?', 'answer' => 'MARIA CLARA'],
            ],
            10 => [
                ['question' => 'LUGAR (8 titik): Ang bayan ng _____ ay matatagpuan malapit sa baybayin ng lawa.', 'answer' => 'SAN DIEGO'],
                ['question' => 'UGALI (9 titik): Ano ang dahilan kung bakit ang mga inaani sa bayan ay binibili ng mga Tsino sa murang halaga?', 'answer' => 'KAHANGALAN'],
                ['question' => 'TAO (4 titik): Sino ang bumibili sa murang halaga ng mga inaani ng mga tao sa San Diego?', 'answer' => 'TSINO'],
                ['question' => 'LUGAR (4 titik): Ano ang natuklasan ng matandang Kastila sa gubat na dinadaluyan ng mainit na tubig?', 'answer' => 'POOK'],
                ['question' => 'BAGAY (5 titik): Bukod sa mga damit at salapi, ano pa ang ibinayad ng matandang Kastila?', 'answer' => 'HIYAS'],
                ['question' => 'KUWENTO (5 titik): Ano ang dahilan kung bakit iginagalang ng mga tao ang gubat?', 'answer' => 'ALAMAT'],
                ['question' => 'TAO (9 titik): Sino ang nakatagpo sa matandang Kastila na nakabitin sa puno?', 'answer' => 'MGA PASTOL'],
                ['question' => 'BAGAY (5 titik): Ano ang mga pinagtatapon ng mga babae sa ilog?', 'answer' => 'HIYAS'],
                ['question' => 'TAO (8 titik): Sino ang natagpuan ng mga pastol na nakabitin sa puno?', 'answer' => 'ANG MATANDA'],
                ['question' => 'TAO (9 titik): Sino ang binatang mestiso na dumating sa pook na nabili ng matandang Kastila?', 'answer' => 'SATURNINO'],
            ],
            11 => [
                ['question' => 'TAO (11 titik): Si _____ ang pinakamayamang tao sa bayan ng San Diego.', 'answer' => 'DON RAFAEL'],
                ['question' => 'TAO (16 titik): Sino ang madalas pagtawanan at tinatawag na "Sakristang Tiago"?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (11 titik): Sino ang humalili kay Padre Damaso nang siya ay maalis sa San Diego?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (7 titik): Sino ang asawa ni Donya Consolacion?', 'answer' => 'ALPERES'],
                ['question' => 'KATUNGKULAN (4 titik): Kaninong kapangyarihan ang inihahalintulad sa Papa sa Batikano?', 'answer' => 'KURA'],
                ['question' => 'GAWAIN (9 titik): Ano ang hilig ni Padre Salvi bukod sa pangingilin?', 'answer' => 'PAGAAYUNO'],
                ['question' => 'TAO (16 titik): Ang Alperes ay sawimpalad dahil sa pagkakapag-asawa kay _____.', 'answer' => 'DONYA CONSOLACION'],
                ['question' => 'GAWAIN (8 titik): Kapag pumapasok ang Alperes, ano ang iniuutos ni Padre Salvi sa sakristan?', 'answer' => 'ISARA ANG PINTO'],
                ['question' => 'DAMIT (7 titik): Ano ang suot ni Donya Consolacion habang nakadungaw?', 'answer' => 'PRANELA'],
                ['question' => 'KATANGIAN (9 titik): Ano ang hitsura ng mga mata ni Donya Consolacion?', 'answer' => 'NANLILISIK'],
            ],
            12 => [
                ['question' => 'BAGAY (4 titik): Sa gitna ng libingan ay may nakatuntong sa bato --- isang _____.', 'answer' => 'KRUS'],
                ['question' => 'LUGAR (8 titik): Ano ang nasa dulo ng makipot na landas sa San Diego?', 'answer' => 'LIBINGAN'],
                ['question' => 'BILANG (6 titik): Ilang tao ang humuhukay ng paglilibingan sa tabi ng pader?', 'answer' => 'DALAWA'],
                ['question' => 'BAGAY (5 titik): Ano ang hinahanap ng matanda na lumapit sa tagapaglibing?', 'answer' => 'BUNGKO'],
                ['question' => 'KATANGIAN (6 titik): Ano ang hitsura ng paligid ng libingan?', 'answer' => 'MASUKAL'],
                ['question' => 'HALAMAN (15 titik): Ano ang nagsisilbing palamuti sa mga bangkay?', 'answer' => 'DAMO AT HALAMAN'],
                ['question' => 'PANGYAYARI (8 titik): Ano ang maaaring mangyari sa pader na katabi ng hinuhukay?', 'answer' => 'BABAGSAK'],
                ['question' => 'BAGAY (12 titik): Sa paanan ng krus, ano ang nakatambak?', 'answer' => 'BUNGKO AT BUTO'],
                ['question' => 'GAWAIN (9 titik): Ano ang ginagawa ng matanda habang lumalapit?', 'answer' => 'NAGHANAP'],
                ['question' => 'BAGAY (6 titik): Ano ang dinukot ng matanda mula sa kanyang bulsa?', 'answer' => 'SALAPI'],
            ],
            13 => [
                ['question' => 'SASAKYAN (7 titik): Si Ibarra ay sakay ng _____ papuntang libingan.', 'answer' => 'KARWAHE'],
                ['question' => 'TAO (12 titik): Sino ang nag-utos na sunugin ang bangkay ni Don Rafael?', 'answer' => 'PADRE GARROTE'],
                ['question' => 'TAO (6 titik): Sino ang dumating sa libingan na lulan ng karwahe?', 'answer' => 'IBARRA'],
                ['question' => 'LUGAR (4 titik): Saan itinapon ng tagapaglibing ang bangkay?', 'answer' => 'LAWA'],
                ['question' => 'AKSYON (10 titik): Ano ang ginawa ni Ibarra kay Padre Salvi?', 'answer' => 'DINALUHONG'],
                ['question' => 'TAO (11 titik): Sino ang nakita ni Ibarra na naka-sombrero at may baston na may puluhang garing?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (6 titik): Sino ang umalis na parang baliw sa libingan?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (6 titik): Sino ang kasunod ni Ibarra sa kanyang pag-alis?', 'answer' => 'MATANDA'],
                ['question' => 'LUGAR (14 titik): Saan papunta si Ibarra matapos umalis sa libingan?', 'answer' => 'PALABAS NG BAYAN'],
                ['question' => 'TAO (13 titik): Sino ang nangakong magpapagawa ng nitso?', 'answer' => 'KAPITAN TIAGO'],
            ],
            14 => [
                ['question' => 'TAO (16 titik): Ang matandang lalaki na palibot-libot sa lansangan ay si _____.', 'answer' => 'PILOSOPONG TASYO'],
                ['question' => 'KATANGIAN (11 titik): Ano ang dahilan kung bakit pinatigil si Mang Tasyo ng kanyang ina sa pag-aaral?', 'answer' => 'KATALINUHAN'],
                ['question' => 'BAGAY (8 titik): Ano ang napabayaan ni Pilosopo Tasyo dahil sa pagbabasa?', 'answer' => 'KAYAMANAN'],
                ['question' => 'LUGAR (8 titik): Saan nagtungo si Pilosopo Tasyo?', 'answer' => 'SIMBAHAN'],
                ['question' => 'TAO (14 titik): Sino ang ayaw magpaalis sa dalawang batang sakristan?', 'answer' => 'SAKRISTAN MAYOR'],
                ['question' => 'LUGAR (10 titik): Saan patungo ang magkapatid upang dupikalin ang kampana?', 'answer' => 'KAMPANARYO'],
                ['question' => 'GAWAIN (8 titik): Ano ang pinili ni Mang Tasyo kaysa magpari?', 'answer' => 'MAGASAWA'],
                ['question' => 'GAWAIN (9 titik): Ano ang itinuring niyang libangan matapos naulila?', 'answer' => 'PAGBABASA'],
                ['question' => 'LUGAR (9 titik): Saan nagtungo si Pilosopong Tasyo matapos lumabas ng simbahan?', 'answer' => 'KABAYANAN'],
                ['question' => 'AKSYON (13 titik): Paano tumugon si Pilosopong Tasyo sa balita tungkol kay Ibarra?', 'answer' => 'NAGKBITBALIKAT'],
            ],
            15 => [
                ['question' => 'TAO (7 titik): Si _____ ang mas matatakutin sa magkapatid.', 'answer' => 'CRISPIN'],
                ['question' => 'BILANG (10 titik): Magkano ang sinasahod ni Basilio sa pagpapatunog ng kampana?', 'answer' => 'DALAWANG PISO'],
                ['question' => 'BILANG (5 titik): Ilang beses nang minultahan ng Sakristan Mayor si Basilio?', 'answer' => 'TATLO'],
                ['question' => 'KASALANAN (7 titik): Ano ang ibinibintang ng Sakristan Mayor kay Crispin?', 'answer' => 'MAGNAKAW'],
                ['question' => 'PARUSA (4 titik): Paano raw siya papatayin ng kura kung hindi mailalabas ang ninakaw?', 'answer' => 'PALO'],
                ['question' => 'UGALI (7 titik): Anong ugali mayroon ang Sakristan Mayor?', 'answer' => 'MANUBOK'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Basilio nang siya ay pinagmulta?', 'answer' => 'TUMUTOL'],
                ['question' => 'AKSYON (9 titik): Anong ginawa ng Sakristan Mayor kay Crispin?', 'answer' => 'KINALADKAD'],
                ['question' => 'TUNOG (9 titik): Ano ang napalitan ng kalabog ng katawan ni Crispin?', 'answer' => 'ALINGAWNGAW'],
                ['question' => 'DAMDAMIN (4 titik): Ano ang naramdaman ni Basilio sa nangyari sa kanyang kapatid?', 'answer' => 'POOT'],
            ],
            16 => [
                ['question' => 'TAO (4 titik): Si _____ ang ina nina Basilio at Crispin.', 'answer' => 'SISA'],
                ['question' => 'AKSYON (10 titik): Ano ang ginagawa sa kanya ng asawa tuwing nauubos ang pansugal nito?', 'answer' => 'SINASAKTAN'],
                ['question' => 'GAWAIN (11 titik): Saan nilulustay ng asawa ni Sisa ang kanyang alahas?', 'answer' => 'PAGSUSUGAL'],
                ['question' => 'TAO (9 titik): Kanino nanghingi ng pindang na usa si Sisa?', 'answer' => 'MANG TASYO'],
                ['question' => 'LUGAR (7 titik): Saan pumitas ng kamatis si Sisa?', 'answer' => 'BAKURAN'],
                ['question' => 'TAO (5 titik): Sino ang hindi inaasahang dumating at umubos ng pagkain?', 'answer' => 'ASAWA'],
                ['question' => 'TAO (7 titik): Sino ang naalala ni Sisa nang makita niya ang asong itim?', 'answer' => 'CRISPIN'],
                ['question' => 'HAYOP (3 titik): Anong hayop ang nagdulot ng malungkot na pangitain kay Sisa?', 'answer' => 'ASO'],
                ['question' => 'PAGKAIN (9 titik): Anong ulam ang binili ni Sisa na idaragdag para sa mga anak?', 'answer' => 'ISDANG TUYO'],
                ['question' => 'BILANG (4 titik): Magkano ang ibinilin na ipatira ng asawa ni Sisa kay Basilio?', 'answer' => 'PISO'],
            ],
            17 => [
                ['question' => 'TAO (7 titik): Si _____ ang kumatok sa pinto ng bahay ni Sisa.', 'answer' => 'BASILIO'],
                ['question' => 'BAGAY (4 titik): Ano ang nakita ni Sisa na umaagos sa noo ni Basilio?', 'answer' => 'DUGO'],
                ['question' => 'TAO (7 titik): Sino ang naiwan sa kumbento?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (5 titik): Ano ang ginamit ni Basilio para makatakas sa kumbento?', 'answer' => 'LUBID'],
                ['question' => 'SALITA (9 titik): Ano ang isinisigaw ng mga kawal na narinig ni Basilio?', 'answer' => 'QUIEN VIVE'],
                ['question' => 'BAGAY (11 titik): Ano ang ibinibintang kay Crispin na kanyang ninakaw?', 'answer' => 'ONSA NG GINTO'],
                ['question' => 'AKSYON (8 titik): Nang mabalitaan ni Basilio na dumating ang kanyang ama, ano ang ginawa niya?', 'answer' => 'SINIYASAT'],
                ['question' => 'TAO (7 titik): Sino ang napanaginipan ni Basilio na pinapalo ng kura?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (11 titik): Ano ang nais kunin ni Basilio upang ipagbili?', 'answer' => 'BUNGANGKAHOY'],
                ['question' => 'BAGAY (4 titik): Ano ang nais gamitin ni Basilio upang manghuli ng ibon?', 'answer' => 'SILO'],
            ],
            18 => [
                ['question' => 'KATANGIAN (8 titik): Napansin ng mga tao na si Padre Salvi ay _____ pagkatapos ng misa.', 'answer' => 'MATAMLAY'],
                ['question' => 'TAO (11 titik): Sino ang nagpasimula ng usapan tungkol sa plenarya?', 'answer' => 'MANANG JUANA'],
                ['question' => 'BILANG (3 titik): Ilang plenarya ang sapat para makahango ng kaluluwa ayon kay Manang Rufa?', 'answer' => 'ISA'],
                ['question' => 'TAO (4 titik): Sino ang dumating na may sunong na bakol?', 'answer' => 'SISA'],
                ['question' => 'BAGAY (5 titik): Ano ang sunong ni Sisa pagpasok sa kumbento?', 'answer' => 'BAKOL'],
                ['question' => 'DAMDAMIN (10 titik): Ano ang naramdaman ni Sisa habang paakyat ng hagdanan?', 'answer' => 'KINAKABAHAN'],
                ['question' => 'UGALI (9 titik): Ano ang ipinakitang pakikitungo ng tagapagluto kay Sisa?', 'answer' => 'PANLALAMIG'],
                ['question' => 'BAGAY (12 titik): Ano ang laman ng bakol na dala ni Sisa?', 'answer' => 'SARIWANG GULAY'],
                ['question' => 'TAO (3 titik): Sino ang nais makausap ni Sisa?', 'answer' => 'PARI'],
                ['question' => 'AKSYON (6 titik): Paano iniayos ni Sisa ang dalang sariwang gulay?', 'answer' => 'MAINGAT'],
            ],
            19 => [
                ['question' => 'TAO (4 titik): Si Ibarra ay nagmamasid sa lawa kasama ang _____.', 'answer' => 'GURO'],
                ['question' => 'LUGAR (4 titik): Saan itinapon ang bangkay ng ama ni Ibarra?', 'answer' => 'LAWA'],
                ['question' => 'TAO (14 titik): Sino ang kasama ng guro sa libing ni Don Rafael?', 'answer' => 'TENYENTE GUEVARRA'],
                ['question' => 'KATANGIAN (15 titik): Ayon sa guro, ito ay tulad ng mabuting bagay ngunit hindi nagtatagal.', 'answer' => 'KAGANDAHANGLOOB'],
                ['question' => 'GAWAIN (13 titik): Ano ang kailangang gawin nina Ibarra upang mapabuti ang pagtuturo?', 'answer' => 'PAGTUTULUNGAN'],
                ['question' => 'TAO (7 titik): Sino ang kailangang mabigyan ng pagganyak upang matuto?', 'answer' => 'KABATAAN'],
                ['question' => 'GAWAIN (9 titik): Ang mga bata ay nasanay sa _____ kaya\'t hindi nila nauunawaan ang binabasa.', 'answer' => 'PAGSASAULO'],
                ['question' => 'TAO (12 titik): Sino ang nagpatawag sa guro sa pamamagitan ng Sakristan Mayor?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Padre Damaso sa guro dahil sa paggamit ng wikang Kastila?', 'answer' => 'KINUTYA'],
                ['question' => 'GAWAIN (8 titik): Ano ang natuklasan ng guro na hindi nakatutulong sa mga bata?', 'answer' => 'PAMAMALO'],
            ],
            20 => [
                ['question' => 'TAO (10 titik): Si _____ ang pinuno ng liberal.', 'answer' => 'DON FILIPO'],
                ['question' => 'BILANG (6 titik): Ilang pangkat ang kasali sa pagpupulong?', 'answer' => 'DALAWA'],
                ['question' => 'GRUPO (11 titik): Ito ang pangkat ng mga matatanda.', 'answer' => 'CONSERBADOR'],
                ['question' => 'GRUPO (7 titik): Ito ay binubuo ng mga kabataan.', 'answer' => 'LIBERAL'],
                ['question' => 'TAO (7 titik): Sino ang pumunta sa tribunal na mainit ang ulo?', 'answer' => 'KAPITAN'],
                ['question' => 'TAO (4 titik): Sino ang kasama ni Ibarra sa pagpunta sa tribunal?', 'answer' => 'GURO'],
                ['question' => 'TAO (14 titik): Sino ang Kapitan na naging kalaban ni Don Rafael?', 'answer' => 'KAPITAN BASILIO'],
                ['question' => 'OKASYON (10 titik): Ano ang pinaghahandaan ng dalawang pangkat?', 'answer' => 'KAPISTAHAN'],
                ['question' => 'TAO (3 titik): Sino ang nagnanais ng komedya sa kapistahan?', 'answer' => 'KURA'],
                ['question' => 'TAO (12 titik): Nang maging matiwasay ang pulong, sino ang humingi ng pahintulot upang magsalita?', 'answer' => 'BATANG KABESA'],
            ],
            21 => [
                ['question' => 'DAMDAMIN (5 titik): Si Sisa ay nakaramdam ng _____ nang makita ang dalawang guwardiya sibil.', 'answer' => 'TAKOT'],
                ['question' => 'TAO (7 titik): Sino ang hinahanap ng mga guwardiya sibil?', 'answer' => 'CRISPIN'],
                ['question' => 'BAGAY (8 titik): Ano ang itinakip ni Sisa sa mukha upang hindi siya makilala?', 'answer' => 'PAMINDONG'],
                ['question' => 'TAO (4 titik): Sino ang nakakulong sa kuwartel?', 'answer' => 'SISA'],
                ['question' => 'TAO (3 titik): Sino ang dahilan ng pagkakakulong ni Sisa?', 'answer' => 'KURA'],
                ['question' => 'LUGAR (8 titik): Saan nakakulong si Sisa?', 'answer' => 'KUWARTEL'],
                ['question' => 'AKSYON (8 titik): Ano ang ginawa ng mga guwardiya kay Sisa?', 'answer' => 'IKINULONG'],
                ['question' => 'TAO (7 titik): Sino ang nagsabi kay Sisa na gawa ng kura ang kanyang pagkakakulong?', 'answer' => 'ALPERES'],
                ['question' => 'KALAGAYAN (7 titik): Ano ang nangyari kay Sisa pagkatapos makulong?', 'answer' => 'NABALIW'],
                ['question' => 'TAO (7 titik): Ang pilas ng baro na nakita ni Sisa ay pag-aari ni _____.', 'answer' => 'BASILIO'],
            ],
            22 => [
                ['question' => 'TAO (11 titik): Sino ang madalas magkamali sa pagmimisa at laging natitigilan?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (17 titik): Sino ang binatang dumating at bumati kay Padre Salvi?', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'TAO (11 titik): Sino ang ayaw maanyayahan sa salu-salo?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (17 titik): Sino ang nag-imbita kay Padre Salvi?', 'answer' => 'CRISOSTOMO IBARRA'],
                ['question' => 'LUGAR (5 titik): Saan gaganapin ang salu-salo?', 'answer' => 'BATIS'],
                ['question' => 'TAO (10 titik): Sino ang sumalubong kay Ibarra sa daanan?', 'answer' => 'ISANG LALAKI'],
                ['question' => 'GAWAIN (5 titik): Ano ang nais ng lalaki kay Ibarra?', 'answer' => 'TULONG'],
                ['question' => 'BILANG (5 titik): Ilang araw ang naging paghahanda sa kapistahan?', 'answer' => 'TATLO'],
                ['question' => 'KATANGIAN (10 titik): Ano ang napuna nila kay Padre Salvi na dahilan ng pagpayat?', 'answer' => 'GANANG KUMAIN'],
                ['question' => 'TAO (6 titik): Kaninong bahay tumuloy si Ibarra?', 'answer' => 'KATIPAN'],
            ],
            23 => [
                ['question' => 'TAO (5 titik): Sino ang pinsan ni Maria Clara na masiyahin?', 'answer' => 'SINANG'],
                ['question' => 'TAO (8 titik): Sino sa mga kaibigan ni Maria Clara ang laging walang imik?', 'answer' => 'VICTORIA'],
                ['question' => 'TAO (6 titik): Sino sa mga kaibigan ni Maria Clara ang maganda at palaisip?', 'answer' => 'NENENG'],
                ['question' => 'BAGAY (6 titik): Ano ang nadatnan nila sa tabi ng lawa?', 'answer' => 'BANGKA'],
                ['question' => 'TAO (8 titik): Sino ang binatang may matikas na anyo at matipunong katawan?', 'answer' => 'BANGKERO'],
                ['question' => 'TAO (13 titik): Kaninong baklad tumuloy sina Maria Clara at Ibarra?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'BAGAY (4 titik): Ano ang ginamit ni Maria Clara sa pag-awit?', 'answer' => 'ALPA'],
                ['question' => 'HAYOP (6 titik): Ano ang nahuli ng baklad?', 'answer' => 'BUWAYA'],
                ['question' => 'BAGAY (6 titik): Ano ang kinuha ni Ibarra upang tulungan ang bangkero?', 'answer' => 'PUNYAL'],
                ['question' => 'TAO (6 titik): Sino ang nagmamay-ari ng baybayin ng gubat?', 'answer' => 'IBARRA'],
            ],
            24 => [
                ['question' => 'TAO (11 titik): Sino ang nagtungo sa gubat?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TUNOG (10 titik): Ano ang narinig ni Padre Salvi sa may batisan?', 'answer' => 'HALAKHAKAN'],
                ['question' => 'LUGAR (11 titik): Saan kumubli si Padre Salvi nang marinig ang halakhakan?', 'answer' => 'PUNONGKAHOY'],
                ['question' => 'TAO (19 titik): Sino ang babaeng payat at marusing na sumipot sa piging?', 'answer' => 'SISA'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Sisa pagkakita sa Alperes?', 'answer' => 'TUMAKBO'],
                ['question' => 'TAO (7 titik): Sino ang nakita ni Sisa kaya siya tumakbo?', 'answer' => 'ALPERES'],
                ['question' => 'BILANG (4 titik): Ilang araw nang nababaliw si Sisa?', 'answer' => 'APAT'],
                ['question' => 'AKLAT (16 titik): Ano ang binabasa ng mga kabinataan?', 'answer' => 'GULONG NG KAPALARAN'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Padre sa aklat na iyon?', 'answer' => 'PINUNIT'],
                ['question' => 'TAO (5 titik): Sino ang tinutukoy ng guwardiya sibil bilang piloto at masamang tao?', 'answer' => 'ELIAS'],
            ],
            25 => [
                ['question' => 'TAO (13 titik): Si Ibarra ay nagtungo sa bahay ni _____.', 'answer' => 'PILOSOPO TASYO'],
                ['question' => 'GAWAIN (10 titik): Ano ang nadatnan niyang ginagawa ng matanda?', 'answer' => 'NAGSUSULAT'],
                ['question' => 'BAGAY (8 titik): Ano ang pangarap ni Ibarra?', 'answer' => 'PAARALAN'],
                ['question' => 'INSTITUSIYON (10 titik): Ayon kay Mang Tasyo, ito ay kasangkapan lamang ng simbahan.', 'answer' => 'PAMAHALAAN'],
                ['question' => 'TAO (10 titik): Sino ang nagunita ni Ibarra habang tinutupad ang kanyang balak?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (7 titik): Saan nanggaling si Ibarra bago magtungo kay Mang Tasyo?', 'answer' => 'BUKIRIN'],
                ['question' => 'BAGAY (10 titik): Ano ang kinuha ni Ibarra sa kanyang kalupi?', 'answer' => 'ILANG PAPEL'],
                ['question' => 'TAO (13 titik): Sino rin ang may pangarap na makapagtayo ng paaralan?', 'answer' => 'PILOSOPO TASYO'],
                ['question' => 'AKSYON (4 titik): Ano ang sadya ni Ibarra kay Mang Tasyo?', 'answer' => 'PAYO'],
                ['question' => 'HALIMBAWA (11 titik): Saan inihalintulad ni Mang Tasyo sina Ibarra?', 'answer' => 'PUNONG GUBAT'],
            ],
            26 => [
                ['question' => 'BUWAN (9 titik): Anong buwan ipinagdiriwang ang pista sa bayan ng San Diego?', 'answer' => 'NOBYEMBRE'],
                ['question' => 'BAGAY (9 titik): Ano ang itinayo sa masayang lansangan ng San Diego?', 'answer' => 'SINGKABAN'],
                ['question' => 'BAGAY (9 titik): Ang _____ ay idaraos sa malaking tolda na tinutukuran ng kawayan.', 'answer' => 'PRUSISYON'],
                ['question' => 'BAGAY (15 titik): Ano ang gaganapin sa itinayong malaking entablado sa liwasan ng bayan?', 'answer' => 'KOMEDYA NG TONDO'],
                ['question' => 'TAO (12 titik): Sino ang napiling magsermon sa umaga?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (14 titik): Sino sa mga kilalang tahur ang may dalang 18,000 piso?', 'answer' => 'KAPITAN JOAQUIN'],
                ['question' => 'TAO (8 titik): Sino ang paulit-ulit na nagbabalita tungkol sa pagpapatayo ng bahay-paaralan?', 'answer' => 'NYOR JUAN'],
                ['question' => 'TAO (6 titik): Sino sa mga kilalang tahur ang Tsino na may puhunan na sampung libo?', 'answer' => 'CARLOS'],
                ['question' => 'TAO (13 titik): Sino sa mga kilalang tahur ang mambabangka?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (8 titik): Sino ang napiling magsermon sa gabi?', 'answer' => 'BANGKERO'],
            ],
            27 => [
                ['question' => 'BAGAY (6 titik): Ano ang pasalubong para kay Maria Clara mula Europa?', 'answer' => 'PIYANO'],
                ['question' => 'DAMDAMIN (5 titik): Ano ang naramdaman ni Maria Clara nang makita niya ang lalaking ketongin?', 'answer' => 'NAAWA'],
                ['question' => 'AKSYON (10 titik): Si Sisa ay _____ ng mga guwardiya sibil.', 'answer' => 'KINALADKAD'],
                ['question' => 'TAO (11 titik): Sino ang nag-ayang umuwi dahil nawala na ang kasayahan?', 'answer' => 'MARIA CLARA'],
                ['question' => 'BAGAY (5 titik): Ano ang ibinigay ni Maria Clara sa lalaking ketongin?', 'answer' => 'AGNOS'],
                ['question' => 'GAWAIN (8 titik): Saan inanyayahan ng kaniyang mga kaibigan si Maria Clara?', 'answer' => 'MAMASYAL'],
                ['question' => 'LUGAR (9 titik): Saan naparaan ang grupo ni Maria Clara?', 'answer' => 'PANULUKAN'],
                ['question' => 'BAGAY (9 titik): Alin sa mga pasalubong ni Ibarra ang may mga brilyante at esmeralda?', 'answer' => 'RELIKARYO'],
                ['question' => 'TAO (8 titik): Ano ang idinahilan ni Ibarra na darating nang anyayahan siya ni Kapitan Tiago na maghapunan?', 'answer' => 'PANAUHIN'],
                ['question' => 'TAO (4 titik): Sino ang lumapit at tumangan sa bisig ng ketongin?', 'answer' => 'SISA'],
            ],
            28 => [
                ['question' => 'LUGAR (7 titik): Saan itinayo ang malaking entablado para sa mga dulang Kastila?', 'answer' => 'LIWASAN'],
                ['question' => 'TAO (9 titik): Sino ang hindi nakadalo sa pagbabasbas ng panukalang bato ng paaralan?', 'answer' => 'G. IBARRA'],
                ['question' => 'KATANGIAN (10 titik): Dahil sa _____, hindi nakadalo si G. Ibarra sa pagbabasbas.', 'answer' => 'KARAMDAMAN'],
                ['question' => 'BAGAY (9 titik): Ano ang sinimulan noong ika-11 ng umaga at iniligid sa simbahan?', 'answer' => 'PRUSISYON'],
                ['question' => 'BAGAY (16 titik): Anong musika ang tinugtog ng mga mayayamang anak sa piyano?', 'answer' => 'ALEMAN AT ITALYANO'],
                ['question' => 'TAO (12 titik): Sino ang nagbigay ng sermon sa misa kantada?', 'answer' => 'PADRE MANUEL'],
                ['question' => 'BAGAY (15 titik): Anong uri ng komedya ang kinagiliwan ng mga Indio?', 'answer' => 'KOMEDYANG TAGALOG'],
                ['question' => 'TAO (12 titik): Sino ang kabilang sa mga panauhin ni Kapitan Tiago bukod kina Padre Salvi at Sibyla?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (9 titik): Saan ipinagdiriwang ang pista na pinamumunuan ng mga Pransiskano?', 'answer' => 'SAN DIEGO'],
                ['question' => 'TAO (6 titik): Ang _____ ang dumating kinahapunan at naanyayahan sa paglalagay ng unang bato.', 'answer' => 'ALKALDE'],
            ],
            29 => [
                ['question' => 'BAGAY (6 titik): Ano ang inasahang magdadala ng higit na kasayahan?', 'answer' => 'MUSIKO'],
                ['question' => 'BAGAY (4 titik): Ano ang ginamit ng mamamayan kasama ang kanilang alahas?', 'answer' => 'BAUL'],
                ['question' => 'DAMDAMIN (8 titik): Ang lalaking may sombrero ay nagpapahiwatig ng _____.', 'answer' => 'MALUNGKOT'],
                ['question' => 'TAO (5 titik): Sino ang tanging lalaking hindi nagpalit ng kasuotan?', 'answer' => 'TASIO'],
                ['question' => 'GAWAIN (11 titik): Saan ibinabatay ng lalaking may sombrero ang kanyang pangangampanya?', 'answer' => 'PAGSASAGAWA'],
                ['question' => 'GAWAIN (7 titik): Ano ang hinamon ng militar sa kanya kung ayaw niya sa sitwasyon?', 'answer' => 'MAGBITIW'],
                ['question' => 'BAGAY (6 titik): Ano ang turing ng lalaking may sumbrero sa tungkulin?', 'answer' => 'PASANIN'],
                ['question' => 'BILANG (6 titik): Ilang banda ng musiko ang nahati sa harap ng simbahan?', 'answer' => 'DALAWA'],
                ['question' => 'ORAS (7 titik): Kailan nagsimula ang prusisyon?', 'answer' => 'IKAWALO'],
                ['question' => 'TAO (6 titik): Sino ang kasama ni San Diego de Alcala sa prusisyon?', 'answer' => 'BIRHEN'],
            ],
            30 => [
                ['question' => 'BAGAY (11 titik): Ano ang dinudumog ng mga tao upang makalapit?', 'answer' => 'AGWA BENDITA'],
                ['question' => 'KATANGIAN (9 titik): Anong uri ng amoy ang nasa simbahan?', 'answer' => 'MASANGSANG'],
                ['question' => 'LUGAR (5 titik): Saan nakapuwesto si Ibarra?', 'answer' => 'SULOK'],
                ['question' => 'LUGAR (10 titik): Malapit sa _____ ang reserved seat ni Maria Clara.', 'answer' => 'ALTAR MAYOR'],
                ['question' => 'TAO (6 titik): Sino ang dumating na kasama ang kagawad?', 'answer' => 'ALKALDE'],
                ['question' => 'BILANG (4 titik): Ilang medalya ang suot ng Alkalde?', 'answer' => 'LIMA'],
                ['question' => 'BAGAY (10 titik): Ano ang narinig bukod sa koro bago magsimula ang misa?', 'answer' => 'KAMPANILYA'],
                ['question' => 'TAO (12 titik): Sino ang nagbigay ng sermon?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'LUGAR (5 titik): Saan daw pupunta ang mga kaluluwa ng nakikinig sa sermon?', 'answer' => 'LANGIT'],
                ['question' => 'HALAGA (8 titik): Magkano ang ibabayad ng bayan sa sermon, kung kaya\'t kailangan nilang marinig iyon?', 'answer' => '250 PISO'],
            ],
            31 => [
                ['question' => 'WIKA (7 titik): Ano ang wika ng sermon na nauunawaan lamang ng mga guwardiya sibil, tulisan, at mga banal?', 'answer' => 'KASTILA'],
                ['question' => 'BAGAY (6 titik): Ano ang inihalintulad sa katangian ni San Diego na kasing liwanag ng araw?', 'answer' => 'BITUIN'],
                ['question' => 'GAWAIN (8 titik): Sa anong paksa ni Padre Damaso hinamon niya ang mga Indio sa huling bahagi ng sermon?', 'answer' => 'PANLALAIT'],
                ['question' => 'GAWAIN (11 titik): Ano ang maikling pagbati ng mga mayayabang na estudyante sa pari?', 'answer' => 'MAGANDANG ARAW'],
                ['question' => 'KATANGIAN (6 titik): Ano ang parusa sa mga eskumulgado o hindi sumasampalataya na uulanin sa dilubyo?', 'answer' => 'PALALO'],
                ['question' => 'BAGAY (8 titik): Ano ang tawag sa sermon ni Padre Damaso patungkol kay Ibarra?', 'answer' => 'PARUNGGIT'],
                ['question' => 'KATANGIAN (11 titik): Ano ang tawag sa mga nag-aaway at nagmumurahan sa simbahan?', 'answer' => 'WALANG GALANG'],
                ['question' => 'KATANGIAN (8 titik): Ano ang bunga ng bagong panahon?', 'answer' => 'KALASWAAN'],
                ['question' => 'BAGAY (5 titik): Ano ang nakasalalay ayon sa binalita kay Ibarra?', 'answer' => 'BUHAY'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ng lalaking may sombrero nang lumapit kay Ibarra?', 'answer' => 'BUMULONG'],
            ],
            32 => [
                ['question' => 'BAGAY (7 titik): Anong malaking bagay ang itatayo sa lugar na kinaroroonan, ayon kay Ibarra?', 'answer' => 'PAARALAN'],
                ['question' => 'TAO (5 titik): Sino ang lumapit at nagpakita ng ngiti kay Ibarra upang ipaalam ang kaniyang bilin?', 'answer' => 'ELIAS'],
                ['question' => 'KATANGIAN (5 titik): Anong kulay ang damit ng taong madilaw na siyang naghanda ng kasangkapang panghugos?', 'answer' => 'DILAW'],
                ['question' => 'TAO (11 titik): Sino ang bumasang may nagniningning na tinig ng mga nakasulat sa bumbong?', 'answer' => 'PADRE SALVI'],
                ['question' => 'BAGAY (9 titik): Ano ang ipinaloob sa kahang kristal kasama ang medalya at iba pa?', 'answer' => 'KASULATAN'],
                ['question' => 'BAGAY (7 titik): Ano ang inilagay ng Alkalde sa hukay bago sinundan ng kura?', 'answer' => 'SEMENTO'],
                ['question' => 'TAO (6 titik): Sa pagdiriwang, sino ang sinundan ng kura sa pagbaba sa hukay habang sinulyapan ang nakabiting bato?', 'answer' => 'IBARRA'],
                ['question' => 'BAGAY (13 titik): Ano ang dala ni Ibarra na gawa sa bakal?', 'answer' => 'KUTSARANG BAKAL'],
                ['question' => 'BAGAY (6 titik): Ano ang tawag sa nasawi o natabunan ng bato?', 'answer' => 'BANGKAY'],
                ['question' => 'BAGAY (4 titik): Ano ang tawag sa makinaryang ginagamit sa pagtaas at pagbaba ng mabibigat na bagay?', 'answer' => 'KALO'],
            ],
            33 => [
                ['question' => 'BAGAY (6 titik): Ano ang napansin ni Crisostomo Ibarra sa braso ni Elias na nagpapahiwatig ng kanyang pagkatao?', 'answer' => 'GURLIS'],
                ['question' => 'TAO (5 titik): Sino ang hindi ipadarakip ni Ibarra?', 'answer' => 'ELIAS'],
                ['question' => 'GAWAIN (9 titik): Ano ang ipinahayag ni Ibarra na hindi niya gagawin kay Elias kahit alam niyang siya ay inuusig?', 'answer' => 'IPADARAKIP'],
                ['question' => 'TAO (5 titik): Sino ang bisita na ikinagulat ni Ibarra?', 'answer' => 'ELIAS'],
                ['question' => 'TAO (5 titik): Ayon kay Elias, sino lamang ang may karapatang kumuha ng buhay at hindi dapat palitan ng tao ang kapangyarihan nito?', 'answer' => 'ANG DIYOS'],
                ['question' => 'KONSEPTO (10 titik): Ayon kay Elias, ito ano ang maaaring pawalang sala ng bulag na hukuman?', 'answer' => 'KATARUNGAN'],
                ['question' => 'TAO (10 titik): Ayon kay Elias, sino ang nasawi sa pangyayari sa bato at hindi si Ibarra?', 'answer' => 'TAMPALASAN'],
                ['question' => 'KALAGAYAN (4 titik): Sa anong kalagayan makatwiran ang pagpatay sa taong may masamang balak ayon sa pagpapatuloy ng pahayag ni Elias?', 'answer' => 'BULAG'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ni Elias sa tanong ni Ibarra ukol sa namatay na taong pinili ring makulong sa halip na tumanggap ng malaking suweldo?', 'answer' => 'INIWASAN'],
                ['question' => 'AKSYON (6 titik): Ano ang hangad ni Ibarra na gawin upang makagawa ng mabuti at hindi masama, at hindi makabuo at hindi makasira?', 'answer' => 'HUMATOL'],
            ],
            34 => [
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Ibarra kay Padre Dámaso matapos niyang banggitin ang masamang sinapit ng kanyang ama?', 'answer' => 'SAKAL'],
                ['question' => 'TAO (12 titik): Sino ang nagmadaling umalis sa hapag matapos makatanggap ng telegrama?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'ORAS (7 titik): Anong oras ng hapon darating ang Heneral ayon sa pag-uusap nila?', 'answer' => 'IKAAPAT'],
                ['question' => 'TAO (12 titik): Sino ang napansin ng isang panauhin na wala sa umpukan?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'KATANGIAN (10 titik): Sa anong paraan bumati si Padre Dámaso sa mga naroon nang siya ay dumating?', 'answer' => 'MAPANLIBAK'],
                ['question' => 'PROPESYON (9 titik): Anong propesyon ang idinudusta ni Padre Dámaso, pati na rin ang mga nagpapagawa sa kanila?', 'answer' => 'ARKITEKTO'],
                ['question' => 'BAGAY (5 titik): Ano ang itinira ni Ibarra kay Padre Dámaso na naging sanhi ng pagkabulagta ng kura?', 'answer' => 'KAMAO'],
                ['question' => 'TAO (8 titik): Ano ang sinabi ni Padre Dámaso na kailangan para sa paaralang ipinatatayo ni Ibarra?', 'answer' => 'DALUBHASA'],
                ['question' => 'TAO (6 titik): Sino ang tanging hindi masaya sa pagdating ni Padre Dámaso sa hapag?', 'answer' => 'IBARRA'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ni Ibarra kay Padre Dámaso sa gitna ng hapunan?', 'answer' => 'ISINALYA'],
                ['question' => 'BAGAY (8 titik): Ano ang sandata na hawak ni Ibarra na nagpatingala sa loob at umangat sa pari?', 'answer' => 'KUTSILYO'],
            ],
            35 => [
                ['question' => 'BAGAY (6 titik): Ano ang mabilis na kumalat sa buong bayan pagkatapos ng insidente sa hapunan?', 'answer' => 'BALITA'],
                ['question' => 'TAO (6 titik): Sino ang nagpalagay na mabuti ang nangyari kay Ibarra dahil nakabayad siya sa kanyang maraming utang?', 'answer' => 'TIYAGO'],
                ['question' => 'GRUPO (9 titik): Sino ang pinaniniwalaang naghihintay sa pagdating ng Kapitan Heneral upang pumanig sa kanya?', 'answer' => 'MATATANDA'],
                ['question' => 'TAO (7 titik): Sino ang kasama ng isang panauhin na nakikipag-usap sa daan tungkol sa nangyari?', 'answer' => 'ALPERES'],
                ['question' => 'KATANGIAN (12 titik): Ano ang sinabi ng isang panauhin na angkop kay Ibarra na nag-isip-matanda?', 'answer' => 'KABALIGTARAN'],
                ['question' => 'BAGAY (6 titik): Ayon sa isang panauhin, ano sana ang hindi nangyari kung nakapagtimpi lamang si Ibarra?', 'answer' => 'PAGSISI'],
                ['question' => 'TAO (12 titik): Sino ang sinabi ng isang panauhin na hindi magpapatawad kay Ibarra dahil sa takot?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'LUGAR (5 titik): Saan nag-uusap ang mga taong-bukid tungkol sa hindi matutuloy na pagtatayo ng paaralan?', 'answer' => 'TOLDA'],
                ['question' => 'BAGAY (8 titik): Ano ang pinaniniwalaang hindi na matutuloy na maipapatayo dahil sa nangyari kay Ibarra?', 'answer' => 'PAARALAN'],
                ['question' => 'KONSEPTO (6 titik): Ano ang dahilan ng isang babae kung bakit ikararangal niya ang mga anak na ipinagtatanggol ang yumao nilang magulang?', 'answer' => 'PAGIBIG'],
                ['question' => 'TAO (11 titik): Ano ang tawag ni Padre Dámaso kay Crisostomo Ibarra kaya hindi na matutuloy ang paaralan?', 'answer' => 'PILIBUSTERO'],
            ],
            36 => [
                ['question' => 'TAO (12 titik): Sino ang nawalan ng malay-tao?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (12 titik): Sino ang nagbawal kay Maria Clara na makipag-usap Kay Ibarra?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (12 titik): Sino ang inaaliw ni Tiya Isabel at Andeng?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (12 titik): Sino Ang dumating na malungkot at basang-basa ng pawis?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (13 titik): Kanino idinaing ni Maria Clara ang kanyang kasawian?', 'answer' => 'BIRHENG MARIA'],
                ['question' => 'TAO (15 titik): Sino ang dumating sa bayan?', 'answer' => 'KAPITAN HENERAL'],
                ['question' => 'AKSYON (11 titik): Ano ang nais ng Kapitan Heneral Kay Maria Clara?', 'answer' => 'MAKIPAGUSAP'],
                ['question' => 'AKSYON (7 titik): Anong ginawa ni Maria Clara sa kanyang silid?', 'answer' => 'NAGTAGO'],
                ['question' => 'TAO (12 titik): Sino Ang nagtungo sa silid na Maria Clara?', 'answer' => 'TIYA ISABEL'],
                ['question' => 'TAO (15 titik): Sino ang nais makipag-usap Kay Maria Clara?', 'answer' => 'KAPITAN HENERAL'],
            ],
            37 => [
                ['question' => 'TAO (7 titik): Kanino ipinagbigay-alam ng Kapitan Heneral na nais niyang makausap ang binatang nakatawag ng kanyang pansin?', 'answer' => 'KAGAWAD'],
                ['question' => 'TAO (6 titik): Sino ang nakasalubong ni Maria Clara sa pintuan at kanyang nakatitigan?', 'answer' => 'IBARRA'],
                ['question' => 'AKSYON (7 titik): Ano ang nais ng Kapitan Heneral Kay Maria Clara bago umalis ng bayan?', 'answer' => 'MAKANIIG'],
                ['question' => 'TAO (12 titik): Sino ang akay ni Kapitan Tiago papasok sa silid?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (6 titik): Sino ang binatang nais makipag-usap sa Kapitan Heneral?', 'answer' => 'IBARRA'],
                ['question' => 'DAMDAMIN (11 titik): Ano ang naramdaman ng mga prayle sa malamig na pakikitungo sa kanila ng Kapitan Heneral?', 'answer' => 'SAMA NG LOOB'],
                ['question' => 'TAO (6 titik): Sino ang nakita ng mga prayle sa silid-antayan?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (7 titik): Sino ang ipinatawag ng Kapitan sa kanyang utusan pagkaalis ni Ibarra?', 'answer' => 'ALKALDE'],
            ],
            38 => [
                ['question' => 'BAGAY (10 titik): Ano ang inilabas sa simbahan sa saliw ng nakakatulig na paputok?', 'answer' => 'PRUSISYON'],
                ['question' => 'TAO (7 titik): Sino ang nagpatayo ng kubol sa tapat ng kanyang bahay?', 'answer' => 'KAPITAN'],
                ['question' => 'BILANG (5 titik): Ilang bata ang may dala ng ciriales na pilak?', 'answer' => 'TATLO'],
                ['question' => 'BAGAY (5 titik): Ano ang nakasabit sa dulo ng kawayan na bitbit ng mga bata?', 'answer' => 'PAROL'],
                ['question' => 'BILANG (5 titik): Ilang wika ang ginamit ng bata sa pagbigkas ng tula?', 'answer' => 'TATLO'],
                ['question' => 'TAO (6 titik): Sino ang napansin ng Kapitan Heneral habang nag-iisip?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (11 titik): Sino ang may magandang tinig na umaawit ng kantang "Ave Maria" ni Gougod?', 'answer' => 'MARIA CLARA'],
                ['question' => 'WIKA (7 titik): Bukod sa mga salitang Latin at Tagalog, ano pang uri ng wika ang ginamit ng bata?', 'answer' => 'KASTILA'],
                ['question' => 'TAO (15 titik): Sino ang nakapansin kay Ibarra na malalim na nag-iisip?', 'answer' => 'KAPITAN HENERAL'],
                ['question' => 'LUGAR (5 titik): Saan nagkatipon-tipon ang mga tao para maghandog ng papuri?', 'answer' => 'KUBOL'],
            ],
            39 => [
                ['question' => 'BAGAY (6 titik): Ano ang laging nakasupalpal sa labi ni Donya Consolacion?', 'answer' => 'TABAKO'],
                ['question' => 'AWITIN (8 titik): Anong uri ng awitin ang narinig mula kay Sisa?', 'answer' => 'KUNDIMAN'],
                ['question' => 'TAO (4 titik): Sino ang umaawit ng malungkot na kundiman?', 'answer' => 'SISA'],
                ['question' => 'TAO (11 titik): Sino ang nakahilig sa silyong malaki na tila nag-aantok?', 'answer' => 'CONSOLACION'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang naramdaman ng Donya ng marinig ang awitin ni Sisa kaya ito\'y kanyang pinatigil?', 'answer' => 'NALUNGKOT'],
                ['question' => 'BAGAY (6 titik): Ito ang ginamit ng Donya sa pagpapasayaw Kay Sisa?', 'answer' => 'LATIGO'],
                ['question' => 'DAMDAMIN (7 titik): Bakit pinaalis ni Donya Consolacion Ang bantay?', 'answer' => 'NAPAHIYA'],
                ['question' => 'TAO (16 titik): Sino ang inutusan ng Donya na paakyatin si Sisa?', 'answer' => 'GUWARDIYA SIBIL'],
                ['question' => 'WIKA (7 titik): Anong wika Ang ginagamit ni Donya Consolacion sa pag-uutos kay Sisa?', 'answer' => 'KASTILA'],
                ['question' => 'AKSYON (6 titik): Ano ang nangyari kay Sisa ng dalasan ng Donya ang pagpalo ng latigo?', 'answer' => 'NABUWAL'],
            ],
            40 => [
                ['question' => 'TAO (9 titik): Sino ang nangangasiwa ng palabas na ginaganap sa liwasan ng bayan?', 'answer' => 'DON FILIPO'],
                ['question' => 'BAGAY (10 titik): Ano ang naging bunga ng pagdating ni Ibarra?', 'answer' => 'ALINGASNGAS'],
                ['question' => 'TAO (10 titik): Sa halip na sa entablado, kanino nakapako ang paningin ni Padre Salvi?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (10 titik): Sino ang lumapit kay Don Filipo?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (8 titik): Sino ang pinagbantaan at pinanagot ni Padre Salvi sa harap ng Diyos?', 'answer' => 'TENYENTE'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ng dalawang guwardiya sibil sa mga musikero upang pigilin ang palabas?', 'answer' => 'HINAGAD'],
                ['question' => 'TAO (12 titik): Sino ang walang tigil ng kadadasal ng litanya sa Latin?', 'answer' => 'TYA ISABEL'],
                ['question' => 'BAGAY (8 titik): Ano ang nabuo sa guni-guni ni Padre Salvi?', 'answer' => 'PANGAITAIN'],
                ['question' => 'PALABAS (8 titik): Anong palabas ang katatapos lang bago nagkagulo ang mga tao?', 'answer' => 'SARSUWELA'],
                ['question' => 'TAO (6 titik): Kanino humingi ng tulong si Don Filipo nang di niya mapayapa ang pulutong?', 'answer' => 'IBARRA'],
            ],
            41 => [
                ['question' => 'TAO (5 titik): Sino ang taga-bukid na panauhin ni Ibarra?', 'answer' => 'ELIAS'],
                ['question' => 'TAO (6 titik): Sino ang pumasok sa laboratoryo ni Ibarra na nagsabing may bisita siyang taga-bukid?', 'answer' => 'UTUSAN'],
                ['question' => 'TAO (11 titik): Sino ang may karamdaman ngunit hindi naman malubha?', 'answer' => 'MARIA CLARA'],
                ['question' => 'BAGAY (5 titik): Ano ang mga inihanda ni Ibarra ng siya ay hindi makatulog dahil sa nangyaring kaguluhan?', 'answer' => 'GAMOT'],
                ['question' => 'DAMDAMIN (10 titik): Ano ang muling naramdaman ni Ibarra pagkaalis ni Elias?', 'answer' => 'KALUNGKUTAN'],
                ['question' => 'TAO (11 titik): Sino ang lalaking may pilat sa kaliwang pisngi na magalang na bumati Kay Ibarra?', 'answer' => 'LUCAS'],
                ['question' => 'DAMDAMIN (6 titik): Ano ang naramdaman ni Ibarra sa patuloy na pangungulit sa kanya ni Lucas?', 'answer' => 'NAYAMOT'],
                ['question' => 'TAO (6 titik): Ayon kay Lucas, sino ang apo ng taong nagbilad sa init sa kanyang ama?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (5 titik): Sino ang kapatid ng taong madilaw na namatay sa paghuhugos ng bato?', 'answer' => 'LUCAS'],
            ],
            42 => [
                ['question' => 'TAO (6 titik): Sino ang pamangkin ni Don Tiburcio na nag-aaral ng pag-aabugado?', 'answer' => 'LINARES'],
                ['question' => 'BILANG (5 titik): Ilan ang panauhin ni Kapitan Tiago?', 'answer' => 'TATLO'],
                ['question' => 'TAO (14 titik): Sino ang Asawa ni Don Tiburcio?', 'answer' => 'DONYA VICTORINA'],
                ['question' => 'TAO (7 titik): Ano ang pangarap na mapangasawa ni Donya Victorina?', 'answer' => 'DAYUHAN'],
                ['question' => 'BAGAY (5 titik): Ano ang nais ibigay ni Linares Kay Padre Damaso?', 'answer' => 'LIHAM'],
                ['question' => 'TAO (10 titik): Sino ang dumating habang nagmiminandal sina Kapitan Tiago at mga panauhin nito?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (8 titik): Siya ay kalihim ng nga ministro sa Espanya?', 'answer' => 'LINARES'],
                ['question' => 'TAO (12 titik): Sino ang hinahanap ni Linares at nais bigyan ng liham?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (15 titik): Sino ang maralitang Kastila ng napadpad sa pulong Luzon?', 'answer' => 'DON TIBURCIO'],
                ['question' => 'INSTITUSYON (12 titik): Saang kaalaman umabot ang panggagamot ni Don Tiburcio ng walang pahintulot?', 'answer' => 'PROTOMEDICATO'],
            ],
            43 => [
                ['question' => 'TAO (11 titik): Siya ay namangha dahil sa nakitang inanyo ni Padre Damaso?', 'answer' => 'MARIA CLARA'],
                ['question' => 'LUGAR (9 titik): Saan nagtungo si Padre Damaso upang ilabas ang kaniyang hinanakit?', 'answer' => 'BALKONAHE'],
                ['question' => 'TAO (12 titik): Sino ang tuloy- tuloy at parang walang nadaraanang tao sa kanyang pagpasok?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (8 titik): Sino ang bayaw ni Padre Damaso?', 'answer' => 'CARLICOS'],
                ['question' => 'AKSYON (5 titik): Ano ang ginawa ni Padre Damaso nang hindi niya napigilan ang kaniyang sama ng loob?', 'answer' => 'UMIYAK'],
                ['question' => 'TAO (5 titik): Sino ang lumapit kay Padre Salvi?', 'answer' => 'LUCAS'],
                ['question' => 'BAGAY (5 titik): Ano ang nadinig ni Padre Salvi habang siya ay malungkot at tila may iniisip?', 'answer' => 'TINIG'],
                ['question' => 'KATANGIAN (11 titik): Ano ang napuna ni Padre Salvi kay Lucas?', 'answer' => 'PAGKUKUNWARI'],
                ['question' => 'INSTITUSYON (16 titik): Saan nag-aral ng abogasya si Linares?', 'answer' => 'UNIVERSIDAD CENTRAL'],
                ['question' => 'KATANGIAN (6 titik): Sa paanong paraan nginitian ni Padre Salvi si Lucas?', 'answer' => 'PAKUTYA'],
            ],
            44 => [
                ['question' => 'GRUPO (12 titik): Sino ang nagbabantay kay Maria Clara habang may sakit?', 'answer' => 'MGA KAIBIGAN'],
                ['question' => 'TAO (11 titik): Sino ang nakaratay sa banig na nabinat ng ito\'y mangumpisal?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (6 titik): Sino ang nagpainom kay Maria Clara ng pildoras na maputi?', 'answer' => 'SINANG'],
                ['question' => 'DAMDAMIN (7 titik): Ano ang nangyari sa kura matapos ang kumpisal?', 'answer' => 'NABALISA'],
                ['question' => 'GAWAIN (13 titik): Ayon kay Padre Salvi, ito ang mas higit na nakabuti sapagkat nakalilinis ng budhi?', 'answer' => 'PANGUNGUMPISAL'],
                ['question' => 'GAWAIN (11 titik): Ano ang pinagpipilitan ni Donya Victorina na utang sa kanyang asawa?', 'answer' => 'PAGPAPAGALING'],
                ['question' => 'TAO (11 titik): Sino ang nagmamasid sa malayo habang nagaganap ang kumpisalan?', 'answer' => 'TIYA ISABEL'],
                ['question' => 'TAO (6 titik): Sino ang may lalakarin sa arsobispo para maalis ang ekskomunyon?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (10 titik): Sino ang tumutol sa sinabi ng Donya at sinabing higit na nakabuti ang pangungumpisal?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (12 titik): Sino ang naglimos at nagpamisa sa lahat ng mapaghimalang Santo?', 'answer' => 'KAPITAN TIAGO'],
            ],
            45 => [
                ['question' => 'LUGAR (10 titik): Saan nagtungo si Elias?', 'answer' => 'KAGUBATAN'],
                ['question' => 'BAGAY (8 titik): Ano ang hawak ng lalaking lumabas sa batongbuhay?', 'answer' => 'REBOLBER'],
                ['question' => 'TAO (5 titik): Sino ang lalaking ang ulo ay natatalian ng panyong may dugo?', 'answer' => 'PABLO'],
                ['question' => 'BAGAY (4 titik): Ano ang tumatanglaw sa yungib na pinanatilihan ng mga lalaking?', 'answer' => 'SULO'],
                ['question' => 'DIREKSYON (6 titik): Saan balak magtungo ni Elias?', 'answer' => 'HILAGA'],
                ['question' => 'AKSYON (9 titik): Ano ang ginawa ng dalawang lalaking anak ni matandang Pablo sa nangyaring kabuktutan?', 'answer' => 'NANGSIYASAT'],
                ['question' => 'AKSYON (10 titik): Ano ang nangyari sa isang anak na lalaki ni matandang Pablo pagkatapos ng nangyaring nakawan sa kumbento?', 'answer' => 'ISINUPLONG'],
                ['question' => 'AKSYON (9 titik): Ano ang nais gawin ni matandang Pablo dahil sa nangyari sa kanyang mga anak?', 'answer' => 'MAGHIGANTI'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ng matanda kay Elias?', 'answer' => 'NIYAKAP'],
                ['question' => 'TAO (6 titik): Sino ang tinutukoy ni Elias na kaibigan ng Kapitan Heneral na maaaring makatulong sa kanila?', 'answer' => 'IBARRA'],
            ],
            46 => [
                ['question' => 'LUGAR (9 titik): Ito ay matatagpuan sa San Diego at nahahati sa tatlong bahagi?', 'answer' => 'SABUNGAN'],
                ['question' => 'BAHAGI (10 titik): Saang panig matatagpuan ang tindahan ng mga hitso, tabako, at pagkain?', 'answer' => 'UNANG PANIG'],
                ['question' => 'TAO (13 titik): Bukod sa mga magsasabong, sino pa ang matatagpuan sa ikatlong panig?', 'answer' => 'SENTENSIYADOR'],
                ['question' => 'BAHAGI (11 titik): Saang panig matatagpuan ang pagtatari ng mga manok?', 'answer' => 'IKALAWANG PANIG'],
                ['question' => 'PALAROAN (7 titik): Ano ang idinaraos sa ikatlong panig?', 'answer' => 'SULTADA'],
                ['question' => 'MANOK (9 titik): Ano ang napagkasunduang paglabanin ni Kapitan Tiago at Kapitan Basilio sa halagang tatlong libong piso?', 'answer' => 'BULIK AT LASAK'],
                ['question' => 'LUGAR (7 titik): Saan idinaraos ang sultada?', 'answer' => 'RUWEDA'],
                ['question' => 'TAO (5 titik): Sino ang nasa harapan ng dalawang magkapatid na nagpapakalansing ng dalawang pisong pilak?', 'answer' => 'LUCAS'],
                ['question' => 'TAO (5 titik): Sino ang may sapantaha na ang lasak ni Kapitan Tiago ang mananalo?', 'answer' => 'BRUNO'],
                ['question' => 'TAO (7 titik): Sino ang kapatid ni Bruno?', 'answer' => 'TARSILO'],
            ],
            47 => [
                ['question' => 'TAO (15 titik): Sino ang natanaw ni Donya Victorina na nananabako habang nakadungaw sa bintana?', 'answer' => 'DONYA CONSOLACION'],
                ['question' => 'TAO (14 titik): Sino ang nagbalak pumasok sa bahay ng alperesa ngunit pinigilan ng mga bantay?', 'answer' => 'DONYA VICTORINA'],
                ['question' => 'KATANGIAN (5 titik): Ano ang paglalarawan ni Donya Victorina sa mga bahay na kanilang nadaraanan?', 'answer' => 'PANGIT'],
                ['question' => 'TAO (16 titik): Sino ang nanaog na may dalang latigo?', 'answer' => 'DONYA CONSOLACION'],
                ['question' => 'AKSYON (5 titik): Ano ang ginawa ng alperesa matapos niyang hagurin ng tingin mula ulo hanggang paa si Donya Victorina?', 'answer' => 'LUMURA'],
                ['question' => 'TAO (7 titik): Sino ang pinagsasabihan ni Donya Victorina na makipaglaban sa alperes gamit ang rebolber?', 'answer' => 'LINARES'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ni Donya Victorina sa pustiso ni Don Tiburcio?', 'answer' => 'DINUROG'],
                ['question' => 'TAO (9 titik): Sino ang nais magsumbong sa Kapitan Heneral?', 'answer' => 'VICTORINA'],
                ['question' => 'DAMDAMIN (8 titik): Ano ang naramdaman ng mga nanonood sa pag-aaway ng dalawang Donya?', 'answer' => 'NASIYAHAN'],
                ['question' => 'BAGAY (5 titik): Ano ang iminungkahing gamit sa laban ni Linares at Alperes?', 'answer' => 'SABLE'],
            ],
            48 => [
                ['question' => 'TAO (12 titik): Kaninong bahay ang unang sinadya ni Ibarra?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'TAO (11 titik): Sino ang unang ninasa na makita ni Ibarra?', 'answer' => 'MARIA CLARA'],
                ['question' => 'TAO (8 titik): Sino ang sumalubong kay Ibarra pagkarating sa pinapatayong paaralan?', 'answer' => 'NYOR JUAN'],
                ['question' => 'TAO (7 titik): Sino ang namalas ni Ibarra na kasama ni Maria Clara sa balkonahe?', 'answer' => 'LINARES'],
                ['question' => 'BAGAY (5 titik): Ano ang hawak ni Ibarra na nagmula sa arsobispo?', 'answer' => 'LIHAM'],
                ['question' => 'TAO (6 titik): Sino ang binatang nagsabi na hindi na siya ekskomulgado?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (9 titik): Sino ang nakasalubong kumain ni Ibarra?', 'answer' => 'ARSOBISPO'],
                ['question' => 'TAO (12 titik): Sino ang taong wala sa bahay pagdating ni Ibarra kinaumagahan?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'BAGAY (6 titik): Ano ang ipinakuha ni Ibarra Kay Nyor Juan?', 'answer' => 'TALAAN'],
                ['question' => 'TAO (5 titik): Sino ang nakita ni Ibarra na kasama ng mga manggagawa?', 'answer' => 'ELIAS'],
            ],
            49 => [
                ['question' => 'LUGAR (4 titik): Saan naganap ang pag-uusap nina Elias at Ibarra habang nakasakay sa bangka?', 'answer' => 'LAWA'],
                ['question' => 'TAO (6 titik): Sino ang lumulan sa bangka ni Elias bago magtakipsilim?', 'answer' => 'IBARRA'],
                ['question' => 'KONSEPTO (10 titik): Anong pagbabago ang hinihiling ng mga sawimpalad ukol sa pamahalaan?', 'answer' => 'KATARUNGAN'],
                ['question' => 'KONSEPTO (9 titik): Ano ang dahilan kung bakit ang mga tulisan ay nananatiling tulisan habambuhay?', 'answer' => 'KALUPITAN'],
                ['question' => 'TAO (5 titik): Sino ang nagdala ng kahilingan ng mga sawimpalad?', 'answer' => 'ELIAS'],
                ['question' => 'KONSEPTO (9 titik): Ano ang hinahangad ng mga sawimpalad mula sa pamahalaan?', 'answer' => 'PAGBABAGO'],
                ['question' => 'KONSEPTO (11 titik): Ano ang kailangan ng pamahalaan upang magpatupad ng batas?', 'answer' => 'KAPANGYARIHAN'],
                ['question' => 'PANAHON (10 titik): Ilang taon nang may guwardiya sibil ngunit may tulisan pa rin?', 'answer' => 'LABINLIMA'],
                ['question' => 'KONSEPTO (10 titik): Ano ang maaaring mawala kapag humina ang guwardiya sibil?', 'answer' => 'KATAHIMIKAN'],
                ['question' => 'AKSYON (12 titik): Ano ang ginagawa ng mga Kastila upang magmukhang may nalalaman?', 'answer' => 'NAGBABALATKAYO'],
            ],
            50 => [
                ['question' => 'PARATANG (10 titik): Ano ang ibinintang sa Nuno ni Elias?', 'answer' => 'MANUNUNOG'],
                ['question' => 'KATANGIAN (11 titik): Anong katangian meron si Elias noong siya ay mag-aaral pa lamang?', 'answer' => 'MAPAGMATAAS'],
                ['question' => 'TAO (5 titik): Siya ay nakilala sa tawag na ito at kinatakutan ang kanyang pangalan?', 'answer' => 'BALAT'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ng nuno ni Elias sa naranasang kasawiang palad?', 'answer' => 'NAGBIGTI'],
                ['question' => 'TAO (8 titik): Sa anong tawag nakilala ang ina ni Balat?', 'answer' => 'HALIPAROT'],
                ['question' => 'BAGAY (6 titik): Saan nakalagay ang pugot na ulo ni Balat?', 'answer' => 'BASKET'],
                ['question' => 'LUGAR (7 titik): Saang lalawigan namasukan bilang manggagawa ang bunsong anak?', 'answer' => 'TAYABAS'],
                ['question' => 'INSTITUSYON (7 titik): Saan nag-aral ng kolehiyo si Elias?', 'answer' => 'HESWITA'],
                ['question' => 'INSTITUSYON (11 titik): Saan ipinasok sa kolehiyo ang kapatid ni Elias?', 'answer' => 'LA CONCORDIA'],
                ['question' => 'LUGAR (8 titik): Saan natagpuan ang bangkay ng babaeng kapatid ni Elias?', 'answer' => 'BAYBAYIN'],
            ],
            51 => [
                ['question' => 'TAO (7 titik): Siya ay nabalisa at nawalan ng kibo dahil sa natanggap na liham mula Kay Donya Victorina?', 'answer' => 'LINARES'],
                ['question' => 'TAO (11 titik): Sino ang nais makausap ni Ibarra ng sarilinan?', 'answer' => 'MARIA CLARA'],
                ['question' => 'PARUSA (9 titik): Anong parusa ang binanta ni Donya Victorina kay Linares kung hindi hahamunin ang Alperes?', 'answer' => 'PAGBUBUNYAG'],
                ['question' => 'TAO (6 titik): Sino ang tinukoy ni Padre Salvi bilang mabuting binata ngunit pabigla-bigla?', 'answer' => 'IBARRA'],
                ['question' => 'BAGAY (5 titik): Ano ang natanggap ni Linares Mula Kay Donya Victorina?', 'answer' => 'LIHAM'],
                ['question' => 'BILANG (5 titik): Ilang araw ang palugit ni Donya Victorina kay Linares para hamunin Ang Alperes?', 'answer' => 'TATLO'],
                ['question' => 'TAO (9 titik): Sino ang nagpadala ng liham kay Linares tungkol sa hamon sa Alperes?', 'answer' => 'VICTORINA'],
                ['question' => 'TAO (12 titik): Sino ang kompesor ni Maria Clara?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (10 titik): Sino ang sumalubong kay Ibarra at buong lugod siyang kinamayan?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (6 titik): Sino ang nilapitan ni Ibarra at dinala sa salas upang makausap?', 'answer' => 'SINANG'],
            ],
            52 => [
                ['question' => 'TAO (5 titik): Sino ang hinahanap ng mga guwardiya sibil?', 'answer' => 'ELIAS'],
                ['question' => 'TAO (5 titik): Sino ang kalaban ni Elias sa paglalaro ng baraha?', 'answer' => 'LUCAS'],
                ['question' => 'BILANG (5 titik): Ilang anino ang nag-uusap sa tagpo?', 'answer' => 'TATLO'],
                ['question' => 'LUGAR (7 titik): Saan nag-usap ang tatlong anino?', 'answer' => 'LIBINGAN'],
                ['question' => 'TAO (4 titik): Sino ang nais gantihan ng mga anino?', 'answer' => 'KURA'],
                ['question' => 'TAO (5 titik): Sino ang nanalo sa paglalaro ng baraha?', 'answer' => 'LUCAS'],
                ['question' => 'LUGAR (8 titik): Saan sasalakay ang isang anino upang masabi na ang kanyang ama ay may anak na lalaki?', 'answer' => 'KUWARTEL'],
                ['question' => 'LUGAR (8 titik): Saan sasalakay ang isang anino upang makaganti sa kura?', 'answer' => 'KUMBENTO'],
            ],
            53 => [
                ['question' => 'TAO (9 titik): Sino ang nagtungo sa bahay ni pilosopo Tasyo?', 'answer' => 'DON FILIPO'],
                ['question' => 'TAO (15 titik): Ayon kay pilosopo Tasyo, sino na ang kalaban ni Don Filipo?', 'answer' => 'GUWARDIYA SIBIL'],
                ['question' => 'TAO (6 titik): Sino ang binanggit na sumunod sa paniniwala ng nakararami?', 'answer' => 'IBARRA'],
                ['question' => 'GAWAIN (9 titik): Ano ang tungkulin ng tenyente?', 'answer' => 'MAGPASUNOD'],
                ['question' => 'TAO (8 titik): Sino ang nais magbitiw sa kanyang tungkulin?', 'answer' => 'TENYENTE'],
                ['question' => 'PANAHON (6 titik): Sa anong panahon kailangang manatili ang pinuno sa tungkulin ayon sa tenyente?', 'answer' => 'DIGMAAN'],
                ['question' => 'TAO (7 titik): Sino ang tinutuligsa sa Europa?', 'answer' => 'HESWITA'],
                ['question' => 'TAO (10 titik): Sino ang kalaban ng mga Heswita sa pagpipista ng mga kolehiyo?', 'answer' => 'DOMINIKANO'],
                ['question' => 'ISYU (11 titik): Ano ang isyung panrelihiyon na tinutukoy sa usapan tungkol kay Ibarra?', 'answer' => 'EKSKOMUNYON'],
                ['question' => 'GRUPO (9 titik): Sino ang masisipag sa bisyo at matatapang sa paggawa ng kahihiyan?', 'answer' => 'MGA BINATA'],
            ],
            54 => [
                ['question' => 'TAO (5 titik): Sino ang dumating sa bahay ni Ibarra?', 'answer' => 'ELIAS'],
                ['question' => 'BAGAY (8 titik): Ano ang nabatid ni Elias patungkol kay Ibarra?', 'answer' => 'PAGAALSA'],
                ['question' => 'AKSYON (7 titik): Ano ang iniutos na gawin ni Elias kay Ibarra sa mga kasulatan?', 'answer' => 'SUNDUIN'],
                ['question' => 'TAO (14 titik): Sino ang taksil na nagbintang sa nuno ni Elias at naging sanhi ng kanilang kasawian?', 'answer' => 'G EIBARRAMENDIA'],
                ['question' => 'BAGAY (7 titik): Ano ano kinuha ni Elias sa sisidlan ng mga sandata?', 'answer' => 'BALARAW'],
                ['question' => 'AKSYON (5 titik): Ano ang nais mangyari ng mga mag-aalsa kay Ibarra?', 'answer' => 'MASWI'],
                ['question' => 'PANAHON (4 titik): Kailan nakatakda ang pag-aalsa?', 'answer' => 'GABI'],
                ['question' => 'TAO (11 titik): Ayon kay Ibarra, sino ang mag-aantay sa kanya sa Gabi?', 'answer' => 'MARIA CLARA'],
            ],
            55 => [
                ['question' => 'TAO (7 titik): Sino ang ayaw makaharap ni Maria Clara sa hapag?', 'answer' => 'LINARES'],
                ['question' => 'TAO (6 titik): Sino ang dumating na nakaluksa at malungkot?', 'answer' => 'IBARRA'],
                ['question' => 'TAO (7 titik): Ano ang isinisigaw ng tatlong tao na pumasok sa bulwagan?', 'answer' => 'TULISAN'],
                ['question' => 'DAMDAMIN (6 titik): Ano ang reaksyon ng lahat ng sila ay makarinig ng putukan?', 'answer' => 'NABIGLA'],
                ['question' => 'TAO (10 titik): Sino ang nanganlong sa likod ng isang haligi?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (7 titik): Sino ang narinig bilang sumisigaw habang tumatakbo at pinapanaog ang kura?', 'answer' => 'ALPERES'],
                ['question' => 'TAO (10 titik): Sino ang pumigil Kay Ibarra na pumanaog?', 'answer' => 'TIYA ISABEL'],
                ['question' => 'TAO (5 titik): Kaninong duguang ulo ang tila nakikita ni Elias?', 'answer' => 'BALAT'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ni Elias sa mga tinipon niyang kasulatan at mga papeles?', 'answer' => 'SINUNOG'],
                ['question' => 'BAGAY (4 titik): Ano ang sumalubong sa mga guwardiya sibil pagkabukas ng pinto sa bahay ni Ibarra?', 'answer' => 'APOY'],
            ],
            56 => [
                ['question' => 'LUGAR (8 titik): Saang lugar nangyari ang kaguluhan?', 'answer' => 'SAN DIEGO'],
                ['question' => 'GRUPO (10 titik): Sino ang nakaramdam ng hilakbot dahil sa nangyaring kaguluhan sa San Diego?', 'answer' => 'MAMAMAYAN'],
                ['question' => 'TAO (9 titik): Sino ang ikinulong matapos ang labanan ng mga guwardiya sibil at kuwardilyero?', 'answer' => 'DON FILIPO'],
                ['question' => 'TAO (11 titik): Sino ang pinagtangkaang agawin ayon sa kumalat na balita?', 'answer' => 'MARIA CLARA'],
                ['question' => 'BAGAY (8 titik): Ano ang nakita ni Elias sa pantalon at manggas ng baro ng sakristan mayor?', 'answer' => 'AMORSEKO'],
                ['question' => 'BILANG (8 titik): Ilan ang tunay na bilang ng mga namatay ayon sa balita?', 'answer' => 'TATLUMPU'],
                ['question' => 'LUGAR (10 titik): Saan nagtipon ang mga tao upang mag-usap at magbalitaan?', 'answer' => 'LANSANGAN'],
                ['question' => 'TAO (12 titik): Sino ang nasugatan sa insidente ayon sa balita?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'BAGAY (6 titik): Ano ang kumalat sa bayan ng San Diego matapos ang insidente?', 'answer' => 'BALITA'],
                ['question' => 'AKSYON (9 titik): Ano raw ang motibong gawin ni Ibarra ayon sa sumbong?', 'answer' => 'MAGHIGANTI'],
            ],
            57 => [
                ['question' => 'TAO (7 titik): Sino ang inilabas mula sa pangaw na nakagapos at luray-luray ang damit?', 'answer' => 'TARSILO'],
                ['question' => 'BILANG (4 titik): Ilan ang bangkay na ipinakita kay Tarsilo?', 'answer' => 'LIMA'],
                ['question' => 'PARAAN (9 titik): Paano isinabit si Tarsilo sa balon?', 'answer' => 'PATIWARIK'],
                ['question' => 'AKSYON (5 titik): Bukod sa pagbuntal, ano pa ang ginawa ng Alperes kay Tarsilo?', 'answer' => 'SINIPA'],
                ['question' => 'TAO (5 titik): Sino sa mga bangkay ang tadtad ng saksak?', 'answer' => 'BRUNO'],
                ['question' => 'BAGAY (6 titik): Saan iginapos si Tarsilo ayon sa utos ng Alperes?', 'answer' => 'BANGKO'],
                ['question' => 'TAO (7 titik): Sino ang taong may hawak ng orasan?', 'answer' => 'ALPERES'],
                ['question' => 'BAGAY (6 titik): Ano ang tinangkang silayan ni Tarsilo bago mawalan ng malay?', 'answer' => 'LANGIT'],
                ['question' => 'TAO (5 titik): Sino sa mga bangkay ang may tali sa leeg?', 'answer' => 'LUCAS'],
                ['question' => 'BAGAY (7 titik): Ano ang hindi na muling makikita o masisilayan ni Tarsilo?', 'answer' => 'LIWANAG'],
            ],
            58 => [
                ['question' => 'LUGAR (9 titik): Saan huminto ang mga kariton na may sakay na bilanggo?', 'answer' => 'TRIBUNAL'],
                ['question' => 'TAO (7 titik): Sino ang seminaristang nakagapos sa eksena?', 'answer' => 'ALBINO'],
                ['question' => 'SASAKYAN (6 titik): Anong uri ng sasakyan ang huminto sa harap ng tribunal?', 'answer' => 'KARITON'],
                ['question' => 'TAO (7 titik): Sino ang lumabas na umiiyak sa eksena?', 'answer' => 'ANTONIO'],
                ['question' => 'TAO (14 titik): Sino ang pumigil sa mga taong gustong sirain ang kariton?', 'answer' => 'KAPITANA MARIA'],
                ['question' => 'AKSYON (9 titik): Ano ang ginawa ni Andong ng makita ang kanyang biyenan?', 'answer' => 'NAPAHAGULGOL'],
                ['question' => 'TAO (7 titik): Sino ang taong batbat ng sandata ang katawan?', 'answer' => 'ALPERES'],
                ['question' => 'GRUPO (8 titik): Mula sa mataas na pook, sino ang mga pinagmamasdan ni Pilosopo Tasyo sa eksena?', 'answer' => 'BILANGGO'],
                ['question' => 'TAO (13 titik): Sino ang bangkay na natagpuan sa pintuan ng bahay?', 'answer' => 'PILOSOPO TASYO'],
                ['question' => 'TAO (6 titik): Sino ang huling bilanggo na inilabas sa eksena?', 'answer' => 'IBARRA'],
            ],
            59 => [
                ['question' => 'INSTITUSYON (7 titik): Ayon sa usap-usapan, saan nagmumula ang mga nagiging pilibustero?', 'answer' => 'HESWITA'],
                ['question' => 'BAGAY (5 titik): Ayon sa prayle, ito ay ibinibigay kahit sa maliit na bagay lamang?', 'answer' => 'MITRA'],
                ['question' => 'TAO (15 titik): Sino ang pinangangaralan ni kapitana Tinchang?', 'answer' => 'KAPITAN TINONG'],
                ['question' => 'LUGAR (11 titik): Saan ginanap ang piging?', 'answer' => 'INTRAMUROS'],
                ['question' => 'PAKSA (8 titik): Ano ang paksa ng usapan ng mga tao sa piging?', 'answer' => 'PAGAALSA'],
                ['question' => 'TAO (10 titik): Sino ang pinsan ni Kapitan Tinong?', 'answer' => 'G PRIMITIVO'],
                ['question' => 'ALAHAS (8 titik): Ano ang inihandog na regalo sa Kapitan Heneral?', 'answer' => 'SINGSING'],
                ['question' => 'TAO (15 titik): Sino ang naghandog ng singsing sa Kapitan Heneral?', 'answer' => 'KAPITANA TINCHANG'],
                ['question' => 'HALAGA (12 titik): Magkano ang halaga ng singsing na pamasko?', 'answer' => 'ISANLIBONG PISO'],
                ['question' => 'TAO (15 titik): Sino ang galit na galit kay Ibarra dahil sa kanyang mga ginawa?', 'answer' => 'KAPITAN HENERAL'],
            ],
            60 => [
                ['question' => 'TAO (11 titik): Sino ang birhen na tinutukoy ni Donya Victorina?', 'answer' => 'MARIA CLARA'],
                ['question' => 'SASAKYAN (6 titik): Anong uri ng sasakyan ang sumadsad sa ibaba ng bahay ni Kapitan Tiago?', 'answer' => 'BANGKA'],
                ['question' => 'TAO (7 titik): Ayon kay Donya Victorina, sino na ang tagapayo ng Kapitan Heneral?', 'answer' => 'LINARES'],
                ['question' => 'BILANG (5 titik): Ilan ang lulan ng bangka na sumadsad sa ibabang bahay ni Kapitan Tiago?', 'answer' => 'DALAWA'],
                ['question' => 'TAO (6 titik): Sino ang lalaking lumundag sa pader?', 'answer' => 'IBARRA'],
                ['question' => 'LUGAR (6 titik): Saan nagtungo si Ibarra matapos lumundag sa pader?', 'answer' => 'ASOTEA'],
                ['question' => 'TAO (12 titik): Sino ang nagsabi na kaiingitan sila ng marami?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'MGA TAO (11 titik): Sino-sino ang lulan ng bangka?', 'answer' => 'ELIAS AT IBARRA'],
                ['question' => 'AKSYON (7 titik): Sino ang nag-alis ng sambalilo at nagpugay kay Maria Clara?', 'answer' => 'ELIAS'],
                ['question' => 'TAO (11 titik): Sino ang paksa ng usapan ng mga kababaihan?', 'answer' => 'MARIA CLARA'],
            ],
            61 => [
                ['question' => 'LUGAR (11 titik): Saan patungo si Ibarra at Elias?', 'answer' => 'SAN GABRIEL'],
                ['question' => 'BAGAY (4 titik): Ano ang ginamit ni Elias upang itago si Ibarra?', 'answer' => 'DAMO'],
                ['question' => 'AKSYON (8 titik): Ano ang ginawa ng mga bantay sa bangka?', 'answer' => 'PINATIGIL'],
                ['question' => 'GRUPO (9 titik): Sino - sino ang napansin ni Elias na nagkakagulo sa tapat ng palasyo?', 'answer' => 'MGA BANTAY'],
                ['question' => 'SASAKYAN (5 titik): Ano ang tawag sa bangkang may sakay ng guwardiya?', 'answer' => 'PALWA'],
                ['question' => 'AKSYON (9 titik): Ano ang ginawa ng mga bantay matapos patigilin sina Elias?', 'answer' => 'NAGTANONG'],
                ['question' => 'LUGAR (5 titik): Saang lugar binalak bumalik ni Elias?', 'answer' => 'PASIG'],
                ['question' => 'PANAHON (11 titik): Kailan ang napagkasunduang tagpuan ni Elias at Ibarra?', 'answer' => 'NOCHE BUENA'],
                ['question' => 'TAO (5 titik): Sino ang tinutugis ng mga guwardiya?', 'answer' => 'ELIAS'],
                ['question' => 'LUGAR (7 titik): Saan ang napagkasunduang tagpuan ni Elias at Ibarra?', 'answer' => 'LIBINGAN'],
                ['question' => 'AKSYON (8 titik): Ano ang ginagawa ng mga guwardiya tuwing lumilitaw si Elias sa ilog?', 'answer' => 'BINABARIL'],
            ],
            62 => [
                ['question' => 'SANHI (10 titik): Ayon sa pahayagan, ano ang dahilan ng pagkamatay ni Ibarra?', 'answer' => 'PAGKALUNOD'],
                ['question' => 'LUGAR (9 titik): Saan nabalitaan ni Maria Clara ang tungkol kay Ibarra?', 'answer' => 'PAHAYAGAN'],
                ['question' => 'TAO (12 titik): Sino ang nagdulot ng kasawian ni Maria Clara?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'AKSYON (8 titik): Ano ang nais gawin ni Maria Clara matapos malaman ang pagkamatay ni Ibarra?', 'answer' => 'MAGMONGHA'],
                ['question' => 'TAO (6 titik): Sino ang nabalitaang nalunod sa lawa ayon sa pahayagan?', 'answer' => 'IBARRA'],
                ['question' => 'BAGAY (8 titik): Ano ang idinulot ni Padre Damaso sa buhay ni Maria Clara?', 'answer' => 'KASAWIAN'],
                ['question' => 'OKASYON (4 titik): Anong okasyon sa buhay ni Maria Clara ang nais masaksihan ni Padre Damaso?', 'answer' => 'KASAL'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ni Maria Clara matapos mabalitaan ang pagkamatay ni Ibarra?', 'answer' => 'HUMIKBI'],
                ['question' => 'TAO (11 titik): Sino ang kaligayahan ni Padre Damaso?', 'answer' => 'MARIA CLARA'],
                ['question' => 'DAMDAMIN (8 titik): Ano ang nararamdaman ni Padre Damaso sa pag-iyak ng kanyang anak?', 'answer' => 'NAGDURUSA'],
            ],
            63 => [
                ['question' => 'TAO (7 titik): Sino ang batang may sugat sa paa na nakaupo sa punong nakabuwal?', 'answer' => 'BASILIO'],
                ['question' => 'PANAHON (10 titik): Ilang buwan na mula nang matagpuan ng pamilya si Basilio?', 'answer' => 'DALAWA'],
                ['question' => 'BAGAY (8 titik): Ano ang nais ihandog ni Basilio sa kanyang ina?', 'answer' => 'AGINALDO'],
                ['question' => 'TAO (5 titik): Sino ang nakita ni Sisa na naging dahilan ng kanyang pagtakbo?', 'answer' => 'TANOD'],
                ['question' => 'AKSYON (11 titik): Ano ang ginawa ni Basilio bago mawalan ng malay?', 'answer' => 'NAGPATIHULOG'],
                ['question' => 'DAMDAMIN (4 titik): Ano ang naramdaman ni Sisa nang makita ang tanod?', 'answer' => 'TAKOT'],
                ['question' => 'BAGAY (13 titik): Ano ang hindi nasilayan ng mahiwagang tao bago siya mamatay?', 'answer' => 'BUKANG LIWAYWAY'],
                ['question' => 'AKSYON (6 titik): Ano ang ginawa ng alilang babae kay Basilio?', 'answer' => 'BINATO'],
                ['question' => 'AKSYON (7 titik): Ano ang ginawa ni Basilio matapos malaman na wala ng hininga ang kanyang ina?', 'answer' => 'TUMANGIS'],
                ['question' => 'AKSYON (5 titik): Ano ang ginawa ni Basilio sa bangkay ng ina?', 'answer' => 'NIYAKAP'],
            ],
            64 => [
                ['question' => 'LUGAR (6 titik): Saan nanirahan si Padre Damaso matapos pumasok ni Maria Clara sa kumbento?', 'answer' => 'MAYNILA'],
                ['question' => 'TAO (11 titik): Sino ang bumigkas ng sermon sa simbahan ng Sta. Clara?', 'answer' => 'PADRE SALVI'],
                ['question' => 'TAO (12 titik): Sino ang natagpuang patay kinabukasan?', 'answer' => 'PADRE DAMASO'],
                ['question' => 'TAO (7 titik): Sino ang inilibing sa libingan ng Paco?', 'answer' => 'LINARES'],
                ['question' => 'BAGAY (6 titik): Saan natagpuan si Padre Damaso nang siya\'y patay na?', 'answer' => 'HIGAAN'],
                ['question' => 'TAO (12 titik): Sino ang nakaramdam ng panghihina ilang linggo bago maging mongha si Maria Clara?', 'answer' => 'KAPITAN TIAGO'],
                ['question' => 'BAGAY (5 titik): Ano ang hinihintay ni Padre Salvi bilang gantimpala?', 'answer' => 'MITRA'],
                ['question' => 'KATANGIAN (8 titik): Ano ang nangyari sa katawan ni Kapitan Tiago dahil sa kanyang karamdaman?', 'answer' => 'NANGAYAYAT'],
                ['question' => 'TAO (7 titik): Sino ang umuwi na sa Espanya?', 'answer' => 'ALPERES'],
                ['question' => 'BAGAY (7 titik): Ano ang laging dala ni Kapitan Tiago habang naglalakad sa gabi?', 'answer' => 'TUNGKOD'],
                ['question' => 'TAO (9 titik): Ayon sa balita, sino ang dahilan ng pagkamatay ni Linares?', 'answer' => 'VICTORINA'],
            ],
        ];

        foreach ($kabanatas as $kabanataId => $items) {
            foreach ($items as $item) {
                GuessWord::create([
                    'kabanata_id' => $kabanataId,
                    'question'    => $item['question'],
                    'answer'      => strtoupper($item['answer']),
                    'pickedChar'  => '',
                ]);
            }
        }
    }
}