<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageGallerySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('image_galleries')->insert([
            [
                'kabanata_id' => 1,
                'title' => 'ISANG SALUSALO',
                'description' => 'Marangyang tahanan sa daang Anluwage, tabi ng ilog Binundok, na naging lugar ng salu-salo para kay Crisostomo Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K1.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 2,
                'title' => 'SI CRISOSTOMO IBARRA',
                'description' => 'Si Juan Crisostomo Ibarra y Magsalin ay binatang anak ni Don Rafael Ibarra na nag-aral sa Europa. Siya ang kababata at kasintahan ni Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K2.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 3,
                'title' => 'ANG HAPUNAN',
                'description' => 'Inumin na nagpapakita ng karangyaan at mainit na sabaw na inihain sa hapunan bilang tanda ng mainit na pagtanggap sa mga panauhin.',
                'image_url' => '/Img/Dashboard/ImageGallery/K3.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 4,
                'title' => 'EREHE AT PILIBUSTERO',
                'description' => 'Si Don Rafael Ibarra ay ama ni Crisostomo Ibarra; dahil sa yaman ay kinainggitan at naparatangan na erehe at pilibustero ni Padre Damaso, at namatay sa piitan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K4.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 5,
                'title' => 'ISANG BITUIN SA GABING MADILIM',
                'description' => 'Si Maria Clara ay mayuming kasintahan at parating nasa isip ni  Crisostomo Ibarra. Siya ang anak ni Donya Pia Alba kay Padre Damaso.',
                'image_url' => '/Img/Dashboard/ImageGallery/K5.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 6,
                'title' => 'SI KAPITAN TIYAGO',
                'description' => 'Si  Don Santiago na kilala bilang Kapitan Tiago ay asawa ni Donya Pia Alba. Siya ang nakagisnang ama ni Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K6.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 7,
                'title' => 'SUYUAN SA ASOTEA',
                'description' => 'Ang pag-uusap at lambingan ng magkasi na sina Ibarra at Maria Clara, na nagbalik-tanaw sa kanilang nakaraan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K7.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 8,
                'title' => 'MGA ALAALA',
                'description' => 'Habang dumaraan sa masayang pook ng Maynila, dito ay naalala ni Ibarra ang maraming alaala.',
                'image_url' => '/Img/Dashboard/ImageGallery/K8.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 9,
                'title' => 'MGA BAGAY-BAGAY UKOL SA BAYAN',
                'description' => 'Si Padre Sibyla ay isang paring Dominikano na lihim na sumusubaybay sa mga kilos ni Ibarra at naglahad ng alitan nito kay Padre Damaso.',
                'image_url' => '/Img/Dashboard/ImageGallery/K9.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 10,
                'title' => 'ANG BAYAN NG SAN DIEGO',
                'description' => 'Isang bayan na napalilibutan ng bukirin at taniman, naitatag ni Saturnino at pinayabong ni Don Rafael; kilala sa gubat na may alamat.',
                'image_url' => '/Img/Dashboard/ImageGallery/K10.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 11,
                'title' => 'ANG MGA MAKAPANGYARIHAN',
                'description' => 'Magkapareho sa antas ng kapangyarihan ngunit madalas magpapingki ang dalawang makapangyarihan sapagkat nagpapaligsahan sa taglay na kapangyarihan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K11.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 12,
                'title' => 'ARAW NG MGA PATAY',
                'description' => 'Isang masukal at madilim na libingan sa San Diego, tanging krus at mga bungo ang makikita. Doon natuklasan ni Ibarra ang paglilipat ng bangkay ng kanyang ama sa utos ng kura.',
                'image_url' => '/Img/Dashboard/ImageGallery/K12.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 13,
                'title' => 'ANG UNANG BANTA NG SIGWA',
                'description' => 'Matinding galit ni Ibarra matapos malaman ang paglilipat at paglapastangan sa bangkay ng kanyang ama, dahilan ng pagsisimula ng sigwa.',
                'image_url' => '/Img/Dashboard/ImageGallery/K13.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 14,
                'title' => 'TASYO, BALIW O PILOSOPO',
                'description' => 'Maalam na matandang tagapayo na nabuhay sa pagbabasa at pag-iisa; kritikal sa lipunan at simbahan kaya’t hindi iginagalang ng nakararami.',
                'image_url' => '/Img/Dashboard/ImageGallery/K14.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 15,
                'title' => 'ANG DALAWANG SAKRISTAN' ,
                'description' => 'Si Crispin at Basilio ay magkapatid na sakristan sa San Diego. Pinagbintangan si Crispin ng pagnanakaw kaya’t pinahirapan ng Sakristan Mayor na may ugaling manubok.',
                'image_url' => '/Img/Dashboard/ImageGallery/K15.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 16,
                'title' => 'SI SISA',
                'description' => 'Si Sisa ay ina nina Crispin at Basilio. Siya ay martir na asawa ni Pedro na pabaya at malupit sa kanyang pamilya.',
                'image_url' => '/Img/Dashboard/ImageGallery/K16.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 17,
                'title' => 'SI BASILIO',
                'description' => 'Nakatatandang anak ni Sisa at sakristan sa San Diego. Mapagmahal, matiisin, at may pangarap na maiahon ang pamilya mula sa kahirapan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K17.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 18,
                'title' => 'MGA KALULUWANG NAGHIHIRAP',
                'description' => 'Ang matuling paglayo ni sisa habang humahagulgol sa iyak dahil sa maling paratang ng kura laban kina Basilio at Crispin.',
                'image_url' => '/Img/Dashboard/ImageGallery/K18.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 19,
                'title' => 'MGA KARANASAN NG ISANG GURO',
                'description' => 'Siya ang nakausap ni Ibarra tungkol sa mga suliranin ng paaralan sa San Diego. Ibinahagi niya ang mga plano ng ama ni Ibarra para sa edukasyon at ang mga hadlang na dulot ng simbahan at ilang magulang.',
                'image_url' => '/Img/Dashboard/ImageGallery/K19.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 20,
                'title' => 'MGA PULONG SA TRIBUNAL',
                'description' => 'Dito nagtipon ang matatanda at kabataan upang pag-usapan ang pista ng San Diego. Pinamunuan ng Kapitan at ng mga kasapi ng dalawang lapian.',
                'image_url' => '/Img/Dashboard/ImageGallery/K20.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 21,
                'title' => 'ANG KASAYSAYAN NG ISANG INA',
                'description' => 'Si Sisa ay dinakip ng gwardya sibil at ikinulong nang walang kasalanan. Sa labis na dalamhati, siya’y tuluyang nabaliw at nagpagala-gala, umaawit habang hinahanap ang kanyang mga anak.',
                'image_url' => '/Img/Dashboard/ImageGallery/K21.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 22,
                'title' => 'LIWANAG AT DILIM',
                'description' => 'Nagtagpo sina Ibarra at Maria Clara tungkol sa pangamba kay Padre Salvi; sa pag-uwi, hiningan siya ng tulong ng asawa ni Sisa.',
                'image_url' => '/Img/Dashboard/ImageGallery/K22.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 23,
                'title' => 'ANG PANGINGISDA',
                'description' => 'Nahuli sa baklad ang isang buwaya. Lumusong si Ibarra at nailigtas ang isang piloto mula sa panganib.',
                'image_url' => '/Img/Dashboard/ImageGallery/K23.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 24,
                'title' => 'SA KAGUBATAN',
                'description' => 'Ang lihim na pagmamasid ni Padre Salvi sa mga dalaga, lalo na kay Maria Clara, habang sila’y naglalakad sa batis.',
                'image_url' => '/Img/Dashboard/ImageGallery/K24.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 25,
                'title' => 'SA BAHAY NG PILOSOPO',
                'description' => 'Kinausap ni Ibarra si Mang Tasyo tungkol sa kanyang planong paaralan, at pinaalalahanan siyang kahit mabigo, ang mabuting binhi’y tutubo at magsisilbi siyang tanglaw sa iba.',
                'image_url' => '/Img/Dashboard/ImageGallery/K25.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 26,
                'title' => 'ANG BISPERAS NG PISTA',
                'description' => 'Masigla ang San Diego sa bisperas ng pista, habang abala rin ang mga manggagawa sa paaralan ni Ibarra na sinuportahan ng mamamayan at nais gawing padrino ng kura.',
                'image_url' => '/Img/Dashboard/ImageGallery/K26.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 27,
                'title' => 'SA PAGTATAKIPSILIM',
                'description' => 'Tumulong si Maria Clara sa ketongin, ngunit nalungkot matapos makita si Sisa at ang pagkahuli sa baliw.',
                'image_url' => '/Img/Dashboard/ImageGallery/K27.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 28,
                'title' => 'ILANG SULAT',
                'description' => 'Marangya ang pista na may prusisyon, misa, at kasayahan; hinangaan si Maria Clara, dumalo ang alkalde sa paaralan ni Ibarra, at nakatanggap ng mga paanyaya sina Luis Chikito at Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K28.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 29,
                'title' => 'KINAUMAGAHAN',
                'description' => 'Sa pista ng San Diego, may prusisyon, misa, at kasayahan. Tampok si Maria Clara, samantalang si Ibarra ay hindi nakadalo dahil may sakit at pinadalhan ng liham ni Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K29.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 30,
                'title' => 'SA SIMBAHAN',
                'description' => 'Mainit at siksikan sa simbahan; nagsermon si Padre Damaso sa Kastila na di gaanong naunawaan ng mga tao.',
                'image_url' => '/Img/Dashboard/ImageGallery/K30.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 31,
                'title' => 'ANG SERMON',
                'description' => 'Nagsermon si Padre Damaso laban sa mga Indio at kay Ibarra, ngunit marami ang inantok; may nagbanta pa sa buhay ni Ibarra sa paghuhulog ng unang bato.',
                'image_url' => '/Img/Dashboard/ImageGallery/K31.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 32,
                'title' => 'ANG KALO',
                'description' => 'Sa pagtatayo ng paaralan, nabanta ang buhay ni Ibarra ngunit nakaligtas; namatay ang lalaking madilaw at binalaan siyang muli ni Elias.',
                'image_url' => '/Img/Dashboard/ImageGallery/K32.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 33,
                'title' => 'MALAYANG PAGKUKURO',
                'description' => 'Dumalaw si Elias kay Ibarra at binalaan siya na may mga kaaway siya; ipinaalala rin niyang ang Diyos lamang ang tunay na hukom.',
                'image_url' => '/Img/Dashboard/ImageGallery/K33.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 34,
                'title' => 'ANG PANANGHALIAN',
                'description' => ' Sa isang pagtitipon, ininsulto ni Padre Damaso ang ama ni Ibarra kaya’t pinagtangkaan niya itong saktan, ngunit napigilan ni Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K34.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 35,
                'title' => 'MGA BALI-BALITA',
                'description' => 'Matapos ang insidente, tinawag na pilibustero si Ibarra; may kumampi at may nanisi sa kanya, kaya nahinto ang pagpapatayo ng paaralan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K35.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 36,
                'title' => 'ANG UNANG SULIRANIN',
                'description' => 'Nahinto ang pagpapakasal nina Ibarra at Maria Clara; nagdalamhati si Maria Clara habang dumating ang Kapitan Heneral at nagulo ang bayan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K36.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 37,
                'title' => 'ANG KAPITAN HENERAL',
                'description' => 'Ang Kapitan Heneral ay ang pinakamakapangyarihan sa Pilipinas. Siya ang lumakad na maalisan ng pagka-ekskomunyon si Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K37.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 38,
                'title' => 'ANG PRUSISYON',
                'description' => 'Pinagdiwang ng bayan ang maringal na prosesyon sa harap ng bahay ni Kapitan Tiago bilang pagpupugay sa mabuting gawain ni Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K38.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 39,
                'title' => 'SI DONYA CONSOLACION',
                'description' => 'Si Donya Consolacion ay asawa ng Alperes. Siya ay dating labandera na may malaswang bibig at pag-uugali.',
                'image_url' => '/Img/Dashboard/ImageGallery/K39.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 40,
                'title' => 'ANG KATWIRAN AT LAKAS',
                'description' => 'Nagulo ang pagtatanghalan dahil sa alitan ng Alperes; nakapako ang tingin ni Padre Salvi kay Maria Clara at kumalat ang alingasngas sa bayan nang dumating si Ibarra..',
                'image_url' => '/Img/Dashboard/ImageGallery/K40.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 41,
                'title' => 'DALAWANG DALAW',
                'description' => 'Dinalaw ni Elias si Ibarra para ipaalam ang sakit at payuhan tungkol sa gulo; sinalubong siya ni Lucas tungkol sa kabayaran, na ikinainis ni Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K41.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 42,
                'title' => 'ANG MAG-ASAWANG DE ESPADAÑA',
                'description' => 'Dinalaw ni Dr. Tiburcio at Donya Victorina si Maria Clara upang gamutin siya; ipinakilala rin ang kanilang pinsan na si Don Alfonso Linares.',
                'image_url' => '/Img/Dashboard/ImageGallery/K42.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 43,
                'title' => 'MGA PANUKALA',
                'description' => 'Si Maria Clara ay namangha kay Padre Damaso; ipinakilala ni Donya Victorina si Linares, at pinauwi ni Padre Salvi si Lucas dahil sa pagsisinungaling nito.',
                'image_url' => '/Img/Dashboard/ImageGallery/K43.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 44,
                'title' => 'PAGSUSURI NG BUDHI',
                'description' => 'Si Maria Clara ay inihanda sa kumpisal; napansin ni Tiya Isabel na hindi nakikinig ang kura, namutla at nabalisa ito pagkatapos.',
                'image_url' => '/Img/Dashboard/ImageGallery/K44.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 45,
                'title' => 'ANG MGA PINAG-UUSIG',
                'description' => 'Si Tandang Pablo ay pinuno ng mga tulisan na ibig tulungan ni Elias.',
                'image_url' => '/Img/Dashboard/ImageGallery/K45.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 46,
                'title' => 'ANG SABUNGAN',
                'description' => 'Si Lucas ay pinayuhan sina Bruno at Tarcilo na gamitin ang h ni Ibarra para sa kanilang plano at sumalakay sa kwartel, na may gantimpala base sa tagumpay.',
                'image_url' => '/Img/Dashboard/ImageGallery/K46.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 47,
                'title' => 'ANG DALAWANG SENYORA',
                'description' => 'Nag-away sina Donya Victorina at Don Tiburcio dahil sa nangyari sa kanila nang asawa ng alperes at sila ay nagtungo sa bahay ni kapitan tiyago; inabisuhan si Linares tungkol sa insidente.',
                'image_url' => '/Img/Dashboard/ImageGallery/K47.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 48,
                'title' => 'ANG TALINGHAGA',
                'description' => 'Si Tiya Isabel ay hipag ni Kapitan Tiago. Siya ang tumulong sa pagpapalaki kay Maria Clara na siyang nagpatuloy kay Ibarra kasabay ng pagsabing pinatawad nas siya ng  arsobispo.',
                'image_url' => '/Img/Dashboard/ImageGallery/K48.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 49,
                'title' => 'ANG TINIG NG MGA INUUSIG',
                'description' => 'Pinag-usapan ni Elias ang epekto ng kalupitan ng gwardya sibil at ang pangangailangan ng pamahalaan na gumawa ng mabuti.',
                'image_url' => '/Img/Dashboard/ImageGallery/K49.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 50,
                'title' => 'ANG KAANAK NI ELIAS',
                'description' => 'Si Elias ay nagkuwento ng hirap at trahedya ng kanyang pamilya, at kung paano siya naging mabuti at kinilala ng iba sa kabila ng nakaraan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K50.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 51,
                'title' => 'MGA PAGBABAGO',
                'description' => 'Linares ay balisa sa liham ni Donya Victorina. Dumating si Ibarra, sinalubong ni Padre Salvi, at nag-usap sila ni Sinang tungkol kay Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K51.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 52,
                'title' => 'ANG BARAHA NG MGA PATAY AT MGA ANINO',
                'description' => 'Ibarra at ang kanyang mga kasama ay nagplano ng paglusob sa kumbento at kwartel. Nagkita sina Lucas at Elias sa gabi upang maglaro ng Baraha ng mga Patay.',
                'image_url' => '/Img/Dashboard/ImageGallery/K52.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 53,
                'title' => 'ANG MABUTING ARAW AY NAKIKILALA SA UMAGA AT MGA ANINO',
                'description' => 'Nag-usap si Don Filipo at Pilosopo-Tao tungkol sa tungkulin, pag-unlad ng kabataan, at maling halimbawa ng matatanda. Nagpaalam siya nang may kalungkutan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K53.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 54,
                'title' => 'LAHAT NG LIHIM AY NABUBUNYAG, WALANG HINDI NAGKAKAMIT NG PARUSA',
                'description' => 'Si Elias ay tinulungan si Ibarra itago at sunugin ang mga kasulatan ngunit natuklasan niya ang kanyang pamilya ni ibarra na ikinabago ni Elias. Maria Clara naghihintay kay Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K54.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 55,
                'title' => 'ANG KAGULUHAN',
                'description' => 'Si Ibarra ay dinakip ng gwardya at dinala sa kwartel, at si Elias ay tinipon at sinunog ang mga kasulatang makapipinsala kay Ibarra habang si Maria Clara at Kapitan Tiago ay apektado sa kaguluhan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K55.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 56,
                'title' => 'MGA SABI-SABI AT KURU-KURO',
                'description' => 'Nanghilakbot sila sa kaguluhan ng bayan, maraming patayan at sunog, si Don Filipo at Ibarra ay nakulong, at maraming namatay o nakatakas. Ang bangkay ni Lucas ay natagpuan na nakita ni Elias.',
                'image_url' => '/Img/Dashboard/ImageGallery/K56.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 57,
                'title' => 'SA ABA NG MGA NALUPIG',
                'description' => 'Si Tarsilo ay pinahirapan at pinatay ng alperes; nagdulot ito ng hinagpis sa kanyang pamilya.',
                'image_url' => '/Img/Dashboard/ImageGallery/K57.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 58,
                'title' => ': ANG ISINUMPA',
                'description' => 'Si Ibarra at ang iba pang bilanggo ay pinahirapan at pinagbintangan; nagdulot ito ng lungkot at pangungulila sa kanilang pamilya.',
                'image_url' => '/Img/Dashboard/ImageGallery/K58.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 59,
                'title' => 'PAG-IBIG SA BAYAN AT SARILING KAPAKANAN',
                'description' => 'Kumalat ang balita tungkol sa hat nagdulot ng gulo; pinagusapan sa piging ang nangyari at galit ng kapitan heneral kay Ibarra.',
                'image_url' => '/Img/Dashboard/ImageGallery/K59.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 60,
                'title' => 'IKAKASAL SI MARIA CLARA',
                'description' => 'Sa bahay ni Kapitan Tiago, tinalakay ang pagpapakasal kay Maria Clara. Nilinaw ni Ibarra ang maling interpretasyon ng liham, at ibinahagi ni Maria ang lihim ng kanyang pagkatao at mga liham ng kanyang ina.',
                'image_url' => '/Img/Dashboard/ImageGallery/K60.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 61,
                'title' => 'ANG HABULAN SA LAWA',
                'description' => 'Hinabol ng guwardiya sina Elias at Ibarra sa lawa. Nagplano si Elias na iligaw ang mga sundalo para mailigtas sila. Habang tumakas sa lawa, humabol sa kanila ang isang bangka ng guwardiya.',
                'image_url' => '/Img/Dashboard/ImageGallery/K61.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 62,
                'title' => 'ANG PAGTATAPAT NI PADRE DAMASO',
                'description' => 'Napahikbi si Maria Clara sa kasal kay Linares at ibinahagi ang lihim niyang nararamdaman. Napaiyak din si Padre Damaso at pinayagan siyang maging mongha.',
                'image_url' => '/Img/Dashboard/ImageGallery/K62.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 63,
                'title' => 'ANG NOCHE BUENA',
                'description' => 'Binalikan ni Basilio ang San Diego at natagpuan ang ina niyang si Sisa na patay. Nagluksa siya at tinulungan ng isang lalaki na ilibing ito, iniwanan siyang kumuha ng kahoy at salapi para sa pag-aaral.',
                'image_url' => '/Img/Dashboard/ImageGallery/K63.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 64,
                'title' => 'HULING KABANATA',
                'description' => 'Phatay sina Padre Damaso at Linares; Si Kapitan Tiago ay humina, Si Donya Victorina ay nagpapanggap pa rin, si alperes ay umuwi na, at wala ng balita kay Maria Clara.',
                'image_url' => '/Img/Dashboard/ImageGallery/K64.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
