<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageGallerySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('image_galleries')->insert([
            [
                'kabanata_id' => 1,
                'title' => 'Kabanata 1',
                'description' => 'Description for Kabanata 1...',
                'image_url' => '/Img/Dashboard/ImageGallery/K1.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 2,
                'title' => 'Kabanata 2',
                'description' => 'Description for Kabanata 2...',
                'image_url' => '/Img/Dashboard/ImageGallery/K2.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 3,
                'title' => 'Kabanata 3',
                'description' => 'Description for Kabanata 3...',
                'image_url' => '/Img/Dashboard/ImageGallery/K3.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 4,
                'title' => 'Kabanata 4',
                'description' => 'Description for Kabanata 4...',
                'image_url' => '/Img/Dashboard/ImageGallery/K4.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 5,
                'title' => 'Kabanata 5',
                'description' => 'Description for Kabanata 5...',
                'image_url' => '/Img/Dashboard/ImageGallery/K5.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 6,
                'title' => 'Kabanata 6',
                'description' => 'Description for Kabanata 6...',
                'image_url' => '/Img/Dashboard/ImageGallery/K6.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 7,
                'title' => 'Kabanata 7',
                'description' => 'Description for Kabanata 7...',
                'image_url' => '/Img/Dashboard/ImageGallery/K7.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 8,
                'title' => 'Kabanata 8',
                'description' => 'Description for Kabanata 8...',
                'image_url' => '/Img/Dashboard/ImageGallery/K8.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 9,
                'title' => 'Kabanata 9',
                'description' => 'Description for Kabanata 9...',
                'image_url' => '/Img/Dashboard/ImageGallery/K9.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 10,
                'title' => 'Kabanata 10',
                'description' => 'Description for Kabanata 10...',
                'image_url' => '/Img/Dashboard/ImageGallery/K10.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 11,
                'title' => 'Kabanata 11',
                'description' => 'Description for Kabanata 11...',
                'image_url' => '/Img/Dashboard/ImageGallery/K11.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 12,
                'title' => 'Kabanata 12',
                'description' => 'Description for Kabanata 12...',
                'image_url' => '/Img/Dashboard/ImageGallery/K12.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 13,
                'title' => 'Kabanata 13',
                'description' => 'Description for Kabanata 13...',
                'image_url' => '/Img/Dashboard/ImageGallery/K13.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 14,
                'title' => 'Kabanata 14',
                'description' => 'Description for Kabanata 14...',
                'image_url' => '/Img/Dashboard/ImageGallery/K14.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 15,
                'title' => 'Kabanata 15',
                'description' => 'Description for Kabanata 15...',
                'image_url' => '/Img/Dashboard/ImageGallery/K15.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 16,
                'title' => 'Kabanata 16',
                'description' => 'Description for Kabanata 16...',
                'image_url' => '/Img/Dashboard/ImageGallery/K16.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 17,
                'title' => 'Kabanata 17',
                'description' => 'Description for Kabanata 17...',
                'image_url' => '/Img/Dashboard/ImageGallery/K17.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 18,
                'title' => 'Kabanata 18',
                'description' => 'Description for Kabanata 18...',
                'image_url' => '/Img/Dashboard/ImageGallery/K18.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 19,
                'title' => 'Kabanata 19',
                'description' => 'Description for Kabanata 19...',
                'image_url' => '/Img/Dashboard/ImageGallery/K19.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 20,
                'title' => 'Kabanata 20',
                'description' => 'Description for Kabanata 20...',
                'image_url' => '/Img/Dashboard/ImageGallery/K20.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 21,
                'title' => 'Kabanata 21',
                'description' => 'Description for Kabanata 21...',
                'image_url' => '/Img/Dashboard/ImageGallery/K21.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 22,
                'title' => 'Kabanata 22',
                'description' => 'Description for Kabanata 22...',
                'image_url' => '/Img/Dashboard/ImageGallery/K22.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 23,
                'title' => 'Kabanata 23',
                'description' => 'Description for Kabanata 23...',
                'image_url' => '/Img/Dashboard/ImageGallery/K23.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 24,
                'title' => 'Kabanata 24',
                'description' => 'Description for Kabanata 24...',
                'image_url' => '/Img/Dashboard/ImageGallery/K24.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 25,
                'title' => 'Kabanata 25',
                'description' => 'Description for Kabanata 25...',
                'image_url' => '/Img/Dashboard/ImageGallery/K25.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 26,
                'title' => 'Kabanata 26',
                'description' => 'Description for Kabanata 26...',
                'image_url' => '/Img/Dashboard/ImageGallery/K26.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 27,
                'title' => 'Kabanata 27',
                'description' => 'Description for Kabanata 27...',
                'image_url' => '/Img/Dashboard/ImageGallery/K27.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 28,
                'title' => 'Kabanata 28',
                'description' => 'Description for Kabanata 28...',
                'image_url' => '/Img/Dashboard/ImageGallery/K28.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 29,
                'title' => 'Kabanata 29',
                'description' => 'Description for Kabanata 29...',
                'image_url' => '/Img/Dashboard/ImageGallery/K29.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 30,
                'title' => 'Kabanata 30',
                'description' => 'Description for Kabanata 30...',
                'image_url' => '/Img/Dashboard/ImageGallery/K30.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 31,
                'title' => 'Kabanata 31',
                'description' => 'Description for Kabanata 31...',
                'image_url' => '/Img/Dashboard/ImageGallery/K31.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 32,
                'title' => 'Kabanata 32',
                'description' => 'Description for Kabanata 32...',
                'image_url' => '/Img/Dashboard/ImageGallery/K32.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 33,
                'title' => 'Kabanata 33',
                'description' => 'Description for Kabanata 33...',
                'image_url' => '/Img/Dashboard/ImageGallery/K33.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 34,
                'title' => 'Kabanata 34',
                'description' => 'Description for Kabanata 34...',
                'image_url' => '/Img/Dashboard/ImageGallery/K34.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 35,
                'title' => 'Kabanata 35',
                'description' => 'Description for Kabanata 35...',
                'image_url' => '/Img/Dashboard/ImageGallery/K35.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 36,
                'title' => 'Kabanata 36',
                'description' => 'Description for Kabanata 36...',
                'image_url' => '/Img/Dashboard/ImageGallery/K36.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 37,
                'title' => 'Kabanata 37',
                'description' => 'Description for Kabanata 37...',
                'image_url' => '/Img/Dashboard/ImageGallery/K37.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 38,
                'title' => 'Kabanata 38',
                'description' => 'Description for Kabanata 38...',
                'image_url' => '/Img/Dashboard/ImageGallery/K38.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 39,
                'title' => 'Kabanata 39',
                'description' => 'Description for Kabanata 39...',
                'image_url' => '/Img/Dashboard/ImageGallery/K39.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 40,
                'title' => 'Kabanata 40',
                'description' => 'Description for Kabanata 40...',
                'image_url' => '/Img/Dashboard/ImageGallery/K40.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 41,
                'title' => 'Kabanata 41',
                'description' => 'Description for Kabanata 41...',
                'image_url' => '/Img/Dashboard/ImageGallery/K41.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 42,
                'title' => 'Kabanata 42',
                'description' => 'Description for Kabanata 42...',
                'image_url' => '/Img/Dashboard/ImageGallery/K42.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 43,
                'title' => 'Kabanata 43',
                'description' => 'Description for Kabanata 43...',
                'image_url' => '/Img/Dashboard/ImageGallery/K43.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 44,
                'title' => 'Kabanata 44',
                'description' => 'Description for Kabanata 44...',
                'image_url' => '/Img/Dashboard/ImageGallery/K44.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 45,
                'title' => 'Kabanata 45',
                'description' => 'Description for Kabanata 45...',
                'image_url' => '/Img/Dashboard/ImageGallery/K45.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 46,
                'title' => 'Kabanata 46',
                'description' => 'Description for Kabanata 46...',
                'image_url' => '/Img/Dashboard/ImageGallery/K46.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 47,
                'title' => 'Mga Alaala',
                'description' => 'Pagbabalik-tanaw sa nakaraan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K47.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 48,
                'title' => 'Sa Pagitan ng Digmaan',
                'description' => 'Paglalarawan ng kaguluhan sa panahon ng labanan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K48.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 49,
                'title' => 'Ang Pag-asa',
                'description' => 'Pag-asa sa kabila ng lahat ng hirap.',
                'image_url' => '/Img/Dashboard/ImageGallery/K49.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 50,
                'title' => 'Pagbagsak',
                'description' => 'Pagbagsak ng mga pangarap at plano.',
                'image_url' => '/Img/Dashboard/ImageGallery/K50.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 51,
                'title' => 'Pagkawala',
                'description' => 'Pagkawala ng isang mahalagang bagay o tao.',
                'image_url' => '/Img/Dashboard/ImageGallery/K51.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 52,
                'title' => 'Pagbubunyag',
                'description' => 'Pagbubunyag ng isang matagal na lihim.',
                'image_url' => '/Img/Dashboard/ImageGallery/K52.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 53,
                'title' => 'Pag-uusap ng Magkasintahan',
                'description' => 'Isang pusong pag-uusap ng dalawang nagmamahalan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K53.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 54,
                'title' => 'Pagdurusa',
                'description' => 'Matinding pagdurusa at sakripisyo ng mga tauhan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K54.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 55,
                'title' => 'Pag-asa at Pananalig',
                'description' => 'Pagpapatuloy ng pananampalataya sa kabila ng unos.',
                'image_url' => '/Img/Dashboard/ImageGallery/K55.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 56,
                'title' => 'Pag-iisa',
                'description' => 'Pag-iisa ng isang tauhan sa gitna ng kaguluhan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K56.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 57,
                'title' => 'Pagbabalik ng Pag-ibig',
                'description' => 'Muling pagbabalik ng pagmamahalan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K57.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 58,
                'title' => 'Pagkikita sa Bayan',
                'description' => 'Isang mahalagang pagtatagpo sa gitna ng bayan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K58.png',
                'category' => 'Lugar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 59,
                'title' => 'Pagbabago ng Damdamin',
                'description' => 'Pagbabago ng pananaw at damdamin ng isang tauhan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K59.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 60,
                'title' => 'Paglipas ng Panahon',
                'description' => 'Pagdaan ng panahon at pagbabagong dala nito.',
                'image_url' => '/Img/Dashboard/ImageGallery/K60.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 61,
                'title' => 'Pagkawala ng Pag-asa',
                'description' => 'Kawalan ng pag-asa ng ilang tauhan.',
                'image_url' => '/Img/Dashboard/ImageGallery/K61.png',
                'category' => 'Simbolo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 62,
                'title' => 'Pagbangon',
                'description' => 'Muling pagbangon sa kabila ng pagkatalo.',
                'image_url' => '/Img/Dashboard/ImageGallery/K62.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 63,
                'title' => 'Pagpapatuloy',
                'description' => 'Pagpapatuloy ng laban at pag-asa.',
                'image_url' => '/Img/Dashboard/ImageGallery/K63.png',
                'category' => 'Tema',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kabanata_id' => 64,
                'title' => 'Kabanata 64',
                'description' => 'Description for Kabanata 64...',
                'image_url' => '/Img/Dashboard/ImageGallery/K64.png',
                'category' => 'Tauhan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
