<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('quizzes')->insert([

            // ===== KABANATA 1 =====
            [
                'kabanata_id'   => 1,
                'question'      => 'Sino ang nanungkulan sa San Diego ng 20 taon?',
                'choice_a'      => 'Padre Sibyla',
                'choice_b'      => 'Padre Damaso',
                'choice_c'      => 'Kapitan Tiago',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Ano ang tawag sa kinatawan ng hari?',
                'choice_a'      => 'Gobernadorcillo',
                'choice_b'      => 'Tenyente Mayor',
                'choice_c'      => 'Heneral',
                'correct_answer'=> 'C',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Sino ang namagitan nang magkainitan sina Padre Damaso at ang Tenyente?',
                'choice_a'      => 'Padre Sibyla',
                'choice_b'      => 'Alperes',
                'choice_c'      => 'Don Rafael',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Sa tabi ng Ilog ng ________ matatagpuan ang bahay ni Kapitan Tiago?',
                'choice_a'      => 'Maynila',
                'choice_b'      => 'Binundok',
                'choice_c'      => 'Europa',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Ilang taon ang naging panunungkulan ni Padre Damaso sa San Diego?',
                'choice_a'      => 'Labinlima',
                'choice_b'      => 'Dalawampu',
                'choice_c'      => 'Sampu',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Ayon sa paniniwala ni Padre Damaso sa Ebanghelyo, ang mga Indio daw ay ________',
                'choice_a'      => 'Masisipag',
                'choice_b'      => 'Mapagpabaya',
                'choice_c'      => 'Mapagmahal',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Sino ang nagpatunay sa sinabi ni Padre Damaso na ang mga Indio ay mangmang at mapagwalang-bahala?',
                'choice_a'      => 'Padre Sibyla',
                'choice_b'      => 'G. Laruja',
                'choice_c'      => 'Donya Victorina',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Ano ang pangalan ng dumating na panauhin na asawa ni Dr. de Espadana?',
                'choice_a'      => 'Donya Consolacion',
                'choice_b'      => 'Donya Victorina',
                'choice_c'      => 'Donya Patrocinio',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Pinatotohanan ni G. Laruja, na wala nang hihigit pa sa mga Indio sa kamangmangan at pagkawalang ________?',
                'choice_a'      => 'Pananampalataya',
                'choice_b'      => 'Utang na Loob',
                'choice_c'      => 'Paggalang',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 1,
                'question'      => 'Ano ang naramdaman ni Padre Damaso at halos mabitawan ang hawak na kopita?',
                'choice_a'      => 'Natua',
                'choice_b'      => 'Nabigla',
                'choice_c'      => 'Nalungkot',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ===== KABANATA 2 =====
            [
                'kabanata_id'   => 2,
                'question'      => 'Sino ang tinutukoy sa kabanata na kababalik lamang mula sa pag-aaral sa Europa?',
                'choice_a'      => 'Padre Damaso',
                'choice_b'      => 'Crisostomo Ibarra',
                'choice_c'      => 'Kapitan Tiago',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Ilang taon ang ipinamalagi ni Ibarra sa pag-aaral sa Europa?',
                'choice_a'      => 'Lima',
                'choice_b'      => 'Pito',
                'choice_c'      => 'Siyam',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Sinong matalik na kakilala ng kanyang ama ang nag-imbita kay Ibarra ng isang pananghalian kinabukasan?',
                'choice_a'      => 'Kapitan Tinong',
                'choice_b'      => 'Don Rafael',
                'choice_c'      => 'Padre Sibyla',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Sino ang nagpakilala kay Ibarra sa salusalo?',
                'choice_a'      => 'Padre Sibyla',
                'choice_b'      => 'Kapitan Tiago',
                'choice_c'      => 'Donya Victorina',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Ano ang pangalan ng ama ni Ibarra?',
                'choice_a'      => 'Don Rafael',
                'choice_b'      => 'Don Saturnino',
                'choice_c'      => 'Don Filipo',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Kaninong umpukan lumapit si Ibarra upang makipagkilala?',
                'choice_a'      => 'Kababaihan',
                'choice_b'      => 'Binata',
                'choice_c'      => 'Prayle',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Sino ang namukhaan ni Ibarra sa umpukan?',
                'choice_a'      => 'Isang guro',
                'choice_b'      => 'Isang makata',
                'choice_c'      => 'Isang artilyero',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Sa pakikipag-usap ni Ibarra sa makata, ano ang bumuhay sa kanyang pagmamahal sa bayan?',
                'choice_a'      => 'Awit',
                'choice_b'      => 'Tula',
                'choice_c'      => 'Nobela',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Sino ang lumapit kay Ibarra matapos ang pakikipag-usap niya sa makata?',
                'choice_a'      => 'Padre Damaso',
                'choice_b'      => 'Kapitan Tinong',
                'choice_c'      => 'G. Laruja',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 2,
                'question'      => 'Tinanggihan ni Ibarra ang alok na pananghalian sa kanya dahil siya ay uuwi na sa ________?',
                'choice_a'      => 'Maynila',
                'choice_b'      => 'San Diego',
                'choice_c'      => 'Europa',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ===== KABANATA 3 =====
            [
                'kabanata_id'   => 3,
                'question'      => 'Anong pagkain ang inihanda ni Kapitan Tiago sa Kabanata 3?',
                'choice_a'      => 'Adobo',
                'choice_b'      => 'Tinola',
                'choice_c'      => 'Sinigang',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Anong pangyayari sa kanyang buhay ang nagunita ni Ibarra sa sinabi ng dating kura?',
                'choice_a'      => 'Kabataan',
                'choice_b'      => 'Paglalakbay',
                'choice_c'      => 'Pag-aaral',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Ano ang sinabi tungkol sa "luklukan" o upuan sa larawan?',
                'choice_a'      => 'Kompesor',
                'choice_b'      => 'Sakristan',
                'choice_c'      => 'Mesang kahoy',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Ano ang pinag-aagawan nina Padre Damaso at Padre Sibyla?',
                'choice_a'      => 'Pera',
                'choice_b'      => 'Kabisera',
                'choice_c'      => 'Lupa',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Saang lugar namalagi si Ibarra?',
                'choice_a'      => 'Europa',
                'choice_b'      => 'Maynila',
                'choice_c'      => 'Espanya',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Alin sa mga lugar na napuntahan ni Ibarra ang itinuturing niyang pangalawang inang bayan?',
                'choice_a'      => 'Espanya',
                'choice_b'      => 'Pilipinas',
                'choice_c'      => 'Alemanya',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Anong parte ng manok ang natapat sa pinggan ni Padre Damaso upang ibagsak niya ang kutsara at isulong ang pinggan?',
                'choice_a'      => 'Leeg at pakpak',
                'choice_b'      => 'Paa at pakpak',
                'choice_c'      => 'Tiyan at atay',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Ayon kay Padre Damaso, ano ang kasamaang dulot ng pagpapaaral sa Europa?',
                'choice_a'      => 'Katamaran',
                'choice_b'      => 'Mapagmataas',
                'choice_c'      => 'Pagiging rebelde',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Sa pag-aagawan ng dalawa, ano ang sinabi ni Padre Sibyla na para kay Padre Damaso?',
                'choice_a'      => 'Luklukan',
                'choice_b'      => 'Pagkain',
                'choice_c'      => 'Inumin',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 3,
                'question'      => 'Ano ang pinag-aaralan muna ni Ibarra bago tumungo sa isang bayan?',
                'choice_a'      => 'Panitikan',
                'choice_b'      => 'Kasaysayan',
                'choice_c'      => 'Agham',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ===== KABANATA 4 =====
            [
                'kabanata_id'   => 4,
                'question'      => 'Sino ang naglalakad na walang tiyak na patutunguhan?',
                'choice_a'      => 'Ibarra',
                'choice_b'      => 'Kapitan Tinong',
                'choice_c'      => 'Padre Sibyla',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Hanggang saan ang narating ni Ibarra sa paglalakad ng walang tiyak na patutunguhan?',
                'choice_a'      => 'Binundok',
                'choice_b'      => 'Maynila',
                'choice_c'      => 'Europa',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Habang naglalakad ano ang biglang naramdaman ni Ibarra?',
                'choice_a'      => 'Kamay',
                'choice_b'      => 'Sakit sa dibdib',
                'choice_c'      => 'Pagod',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Saan pinasasaringan ni Padre Damaso ang ama ni Ibarra?',
                'choice_a'      => 'Pulpito',
                'choice_b'      => 'Plaza',
                'choice_c'      => 'Bahay ni Kapitan Tiago',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Saan kilala ang dating artilyero na naalis sa pagkasundalo?',
                'choice_a'      => 'Tapang',
                'choice_b'      => 'Kamangmangan',
                'choice_c'      => 'Kayamanan',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Ano ang ipinaratang sa ama ni Ibarra?',
                'choice_a'      => 'Tulisan',
                'choice_b'      => 'Pilibustero',
                'choice_c'      => 'Magnanakaw',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Siya ay sumuka ng dugo at namatay?',
                'choice_a'      => 'Sakristan',
                'choice_b'      => 'Artilyero',
                'choice_c'      => 'Kapitan',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Ano ang isinakdal sa ama ni Ibarra?',
                'choice_a'      => 'Nangangamkam',
                'choice_b'      => 'Magnanakaw',
                'choice_c'      => 'Taksil',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Ano ang iba pang ibinintang sa ama ni Ibarra?',
                'choice_a'      => 'Tulisan',
                'choice_b'      => 'Manloloko',
                'choice_c'      => 'Rebelde',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 4,
                'question'      => 'Ano ang sinakyan ni Ibarra papuntang Fonda de Lala?',
                'choice_a'      => 'Bangka',
                'choice_b'      => 'Kalesa',
                'choice_c'      => 'Karwahe',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ===== KABANATA 5 =====
            [
                'kabanata_id'   => 5,
                'question'      => 'Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra?',
                'choice_a'      => 'Gitara',
                'choice_b'      => 'Biyulin',
                'choice_c'      => 'Plawta',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Sino ang dalagang parating laman ng isip ni Ibarra?',
                'choice_a'      => 'Maria Clara',
                'choice_b'      => 'Donya Victorina',
                'choice_c'      => 'Sisa',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Saang lugar nanggaling si Maria Clara?',
                'choice_a'      => 'Beateryo',
                'choice_b'      => 'Kumbento',
                'choice_c'      => 'Maynila',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Ilan ang pangitain na namalas ni Ibarra sa kalawakan?',
                'choice_a'      => 'Isa',
                'choice_b'      => 'Dalawa',
                'choice_c'      => 'Tatlo',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Sa pangitain ni Ibarra, sino ang nakita niyang lalaking naghihirap sa kulungan?',
                'choice_a'      => 'Kaibigan',
                'choice_b'      => 'Ama',
                'choice_c'      => 'Artilyero',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Ano ang namatay sa katapat na bahay ni Ibarra?',
                'choice_a'      => 'Ilaw',
                'choice_b'      => 'Kandila',
                'choice_c'      => 'Lampara',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Ano ang nararamdaman ni Ibarra nang umupo siya sa isang silyon?',
                'choice_a'      => 'Masaya',
                'choice_b'      => 'Balisang-balisa',
                'choice_c'      => 'Payapa',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Sa pangitain ni Ibarra, sino ang nakita niyang binatang maligaya sa ibayong dagat?',
                'choice_a'      => 'Kaibigan',
                'choice_b'      => 'Kanyang sarili',
                'choice_c'      => 'Ama niya',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Saang parte ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?',
                'choice_a'      => 'Sa pinto',
                'choice_b'      => 'Sa durungawan',
                'choice_c'      => 'Sa hagdanan',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 5,
                'question'      => 'Sino ang tinutukoy na magandang pangitain, isang napakaganda\'t mayuming dilag na nakadamit pilipina?',
                'choice_a'      => 'Sisa',
                'choice_b'      => 'Donya Victorina',
                'choice_c'      => 'Maria Clara',
                'correct_answer'=> 'C',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ===== KABANATA 6 =====
            [
                'kabanata_id'   => 6,
                'question'      => 'Ito ang himig ng tugtugin na nanuot sa pandinig ni Ibarra?',
                'choice_a'      => 'Gitara',
                'choice_b'      => 'Biyulin',
                'choice_c'      => 'Plawta',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Sino ang dalagang parating laman ng isip ni Ibarra?',
                'choice_a'      => 'Maria Clara',
                'choice_b'      => 'Donya Victorina',
                'choice_c'      => 'Sisa',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Saang lugar nanggaling si Maria Clara?',
                'choice_a'      => 'Beateryo',
                'choice_b'      => 'Kumbento',
                'choice_c'      => 'Maynila',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Ilan ang pangitain na namalas ni Ibarra sa kalawakan?',
                'choice_a'      => 'Isa',
                'choice_b'      => 'Dalawa',
                'choice_c'      => 'Tatlo',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Sa pangitain ni Ibarra, sino ang nakita niyang lalaking naghihirap sa kulungan?',
                'choice_a'      => 'Kaibigan',
                'choice_b'      => 'Ama',
                'choice_c'      => 'Artilyero',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Ano ang namatay sa katapat na bahay ni Ibarra?',
                'choice_a'      => 'Ilaw',
                'choice_b'      => 'Kandila',
                'choice_c'      => 'Lampara',
                'correct_answer'=> 'A',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Ano ang nararamdaman ni Ibarra nang umupo siya sa isang silyon?',
                'choice_a'      => 'Masaya',
                'choice_b'      => 'Balisang-balisa',
                'choice_c'      => 'Payapa',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Sa pangitain ni Ibarra, sino ang nakita niyang binatang maligaya sa ibayong dagat?',
                'choice_a'      => 'Kaibigan',
                'choice_b'      => 'Kanyang sarili',
                'choice_c'      => 'Ama niya',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Saang parte ng kanyang silid natatanaw ni Ibarra ang bahay na nagliliwanag sa kabilang ibayo?',
                'choice_a'      => 'Sa pinto',
                'choice_b'      => 'Sa durungawan',
                'choice_c'      => 'Sa hagdanan',
                'correct_answer'=> 'B',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'kabanata_id'   => 6,
                'question'      => 'Sino ang tinutukoy na magandang pangitain, isang napakaganda\'t mayuming dilag na nakadamit pilipina?',
                'choice_a'      => 'Sisa',
                'choice_b'      => 'Donya Victorina',
                'choice_c'      => 'Maria Clara',
                'correct_answer'=> 'C',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

        ]);
    }
}